// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

import * as fc from 'fast-check';
import { DataTransferRate } from '../src/DataTransferRate';

it('From Bits Per Second to KiloBits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.BitsPerSecond.toKiloBitsPerSecond(value)
            const convertBack = DataTransferRate.KiloBitsPerSecond.toBitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Bits Per Second to KiloBits Per Second', () => {
    expect(DataTransferRate.BitsPerSecond.toKiloBitsPerSecond(100.0)).toBeCloseTo(0.1, 1);
    expect(DataTransferRate.BitsPerSecond.toKiloBitsPerSecond(6021.0)).toBeCloseTo(6.021, 1);
    expect(DataTransferRate.BitsPerSecond.toKiloBitsPerSecond(9100.0)).toBeCloseTo(9.1, 1);
});

it('From Bits Per Second to MegaBits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.BitsPerSecond.toMegaBitsPerSecond(value)
            const convertBack = DataTransferRate.MegaBitsPerSecond.toBitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Bits Per Second to MegaBits Per Second', () => {
    expect(DataTransferRate.BitsPerSecond.toMegaBitsPerSecond(9000000.0)).toBeCloseTo(9.0, 1);
    expect(DataTransferRate.BitsPerSecond.toMegaBitsPerSecond(123456.0)).toBeCloseTo(0.123456, 1);
    expect(DataTransferRate.BitsPerSecond.toMegaBitsPerSecond(1900000.0)).toBeCloseTo(1.9, 1);
});

it('From Bits Per Second to GigaBits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.BitsPerSecond.toGigaBitsPerSecond(value)
            const convertBack = DataTransferRate.GigaBitsPerSecond.toBitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Bits Per Second to GigaBits Per Second', () => {
    expect(DataTransferRate.BitsPerSecond.toGigaBitsPerSecond(190000000.0)).toBeCloseTo(0.19, 1);
    expect(DataTransferRate.BitsPerSecond.toGigaBitsPerSecond(8009.0)).toBeCloseTo(8.009e-6, 1);
    expect(DataTransferRate.BitsPerSecond.toGigaBitsPerSecond(987654321.0)).toBeCloseTo(0.987654321, 1);
});

it('From Bits Per Second to TeraBits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.BitsPerSecond.toTeraBitsPerSecond(value)
            const convertBack = DataTransferRate.TeraBitsPerSecond.toBitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Bits Per Second to TeraBits Per Second', () => {
    expect(DataTransferRate.BitsPerSecond.toTeraBitsPerSecond(987654321234.0)).toBeCloseTo(0.987654321234, 1);
    expect(DataTransferRate.BitsPerSecond.toTeraBitsPerSecond(1234567890123456.0)).toBeCloseTo(1234.567890123455982, 1);
    expect(DataTransferRate.BitsPerSecond.toTeraBitsPerSecond(999888777666555.0)).toBeCloseTo(999.888777666555029, 1);
});

it('From Bits Per Second to KiloBytes Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.BitsPerSecond.toKiloBytesPerSecond(value)
            const convertBack = DataTransferRate.KiloBytesPerSecond.toBitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Bits Per Second to KiloBytes Per Second', () => {
    expect(DataTransferRate.BitsPerSecond.toKiloBytesPerSecond(900.0)).toBeCloseTo(0.1125, 1);
    expect(DataTransferRate.BitsPerSecond.toKiloBytesPerSecond(12345.0)).toBeCloseTo(1.543125, 1);
    expect(DataTransferRate.BitsPerSecond.toKiloBytesPerSecond(6000.9)).toBeCloseTo(0.7501125, 1);
});

it('From Bits Per Second to MegaBytes Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.BitsPerSecond.toMegaBytesPerSecond(value)
            const convertBack = DataTransferRate.MegaBytesPerSecond.toBitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Bits Per Second to MegaBytes Per Second', () => {
    expect(DataTransferRate.BitsPerSecond.toMegaBytesPerSecond(123456.0)).toBeCloseTo(0.015432, 1);
    expect(DataTransferRate.BitsPerSecond.toMegaBytesPerSecond(900800.0)).toBeCloseTo(0.1126, 1);
    expect(DataTransferRate.BitsPerSecond.toMegaBytesPerSecond(999888777.0)).toBeCloseTo(124.986097125, 1);
});

it('From Bits Per Second to GigaBytes Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.BitsPerSecond.toGigaBytesPerSecond(value)
            const convertBack = DataTransferRate.GigaBytesPerSecond.toBitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Bits Per Second to GigaBytes Per Second', () => {
    expect(DataTransferRate.BitsPerSecond.toGigaBytesPerSecond(999888777.0)).toBeCloseTo(0.124986097125, 1);
    expect(DataTransferRate.BitsPerSecond.toGigaBytesPerSecond(1.9e+9)).toBeCloseTo(0.2375, 1);
    expect(DataTransferRate.BitsPerSecond.toGigaBytesPerSecond(80090077.0)).toBeCloseTo(0.010011259625, 1);
});

it('From Bits Per Second to TeraBytes Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.BitsPerSecond.toTeraBytesPerSecond(value)
            const convertBack = DataTransferRate.TeraBytesPerSecond.toBitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Bits Per Second to TeraBytes Per Second', () => {
    expect(DataTransferRate.BitsPerSecond.toTeraBytesPerSecond(999888777666.0)).toBeCloseTo(0.12498609720825, 1);
    expect(DataTransferRate.BitsPerSecond.toTeraBytesPerSecond(12345678912345.0)).toBeCloseTo(1.5432098640431251, 1);
    expect(DataTransferRate.BitsPerSecond.toTeraBytesPerSecond(111999222888333.0)).toBeCloseTo(13.9999028610416243, 1);
});

it('From Bits Per Second to Kibibits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.BitsPerSecond.toKibibitsPerSecond(value)
            const convertBack = DataTransferRate.KibibitsPerSecond.toBitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Bits Per Second to Kibibits Per Second', () => {
    expect(DataTransferRate.BitsPerSecond.toKibibitsPerSecond(1800.0)).toBeCloseTo(1.757813, 1);
    expect(DataTransferRate.BitsPerSecond.toKibibitsPerSecond(888.0)).toBeCloseTo(0.867188, 1);
    expect(DataTransferRate.BitsPerSecond.toKibibitsPerSecond(7687.0)).toBeCloseTo(7.506836, 1);
});

it('From Bits Per Second to Mebibits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.BitsPerSecond.toMebibitsPerSecond(value)
            const convertBack = DataTransferRate.MebibitsPerSecond.toBitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Bits Per Second to Mebibits Per Second', () => {
    expect(DataTransferRate.BitsPerSecond.toMebibitsPerSecond(999888.0)).toBeCloseTo(0.953567505, 1);
    expect(DataTransferRate.BitsPerSecond.toMebibitsPerSecond(1234567.0)).toBeCloseTo(1.17737484, 1);
    expect(DataTransferRate.BitsPerSecond.toMebibitsPerSecond(900800.0)).toBeCloseTo(0.859069824, 1);
});

it('From GigaBits Per Second to Bits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.GigaBitsPerSecond.toBitsPerSecond(value)
            const convertBack = DataTransferRate.BitsPerSecond.toGigaBitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known GigaBits Per Second to Bits Per Second', () => {
    expect(DataTransferRate.GigaBitsPerSecond.toBitsPerSecond(0.0009)).toBeCloseTo(900000.0, 1);
    expect(DataTransferRate.GigaBitsPerSecond.toBitsPerSecond(0.00007)).toBeCloseTo(70000.0, 1);
    expect(DataTransferRate.GigaBitsPerSecond.toBitsPerSecond(1.2e-5)).toBeCloseTo(12000.0, 1);
});

it('From GigaBits Per Second to KiloBits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.GigaBitsPerSecond.toKiloBitsPerSecond(value)
            const convertBack = DataTransferRate.KiloBitsPerSecond.toGigaBitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known GigaBits Per Second to KiloBits Per Second', () => {
    expect(DataTransferRate.GigaBitsPerSecond.toKiloBitsPerSecond(0.01)).toBeCloseTo(10000.0, 1);
    expect(DataTransferRate.GigaBitsPerSecond.toKiloBitsPerSecond(0.91)).toBeCloseTo(910000.0, 1);
    expect(DataTransferRate.GigaBitsPerSecond.toKiloBitsPerSecond(6.1)).toBeCloseTo(6.1e+6, 1);
});

it('From GigaBits Per Second to MegaBits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.GigaBitsPerSecond.toMegaBitsPerSecond(value)
            const convertBack = DataTransferRate.MegaBitsPerSecond.toGigaBitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known GigaBits Per Second to MegaBits Per Second', () => {
    expect(DataTransferRate.GigaBitsPerSecond.toMegaBitsPerSecond(6.1)).toBeCloseTo(6100.0, 1);
    expect(DataTransferRate.GigaBitsPerSecond.toMegaBitsPerSecond(0.961)).toBeCloseTo(961.0, 1);
    expect(DataTransferRate.GigaBitsPerSecond.toMegaBitsPerSecond(1.2e-3)).toBeCloseTo(1.2, 1);
});

it('From GigaBits Per Second to TeraBits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.GigaBitsPerSecond.toTeraBitsPerSecond(value)
            const convertBack = DataTransferRate.TeraBitsPerSecond.toGigaBitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known GigaBits Per Second to TeraBits Per Second', () => {
    expect(DataTransferRate.GigaBitsPerSecond.toTeraBitsPerSecond(1200.0)).toBeCloseTo(1.2, 1);
    expect(DataTransferRate.GigaBitsPerSecond.toTeraBitsPerSecond(90012.0)).toBeCloseTo(90.012, 1);
    expect(DataTransferRate.GigaBitsPerSecond.toTeraBitsPerSecond(8000.0)).toBeCloseTo(8.0, 1);
});

it('From GigaBits Per Second to KiloBytes Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.GigaBitsPerSecond.toKiloBytesPerSecond(value)
            const convertBack = DataTransferRate.KiloBytesPerSecond.toGigaBitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known GigaBits Per Second to KiloBytes Per Second', () => {
    expect(DataTransferRate.GigaBitsPerSecond.toKiloBytesPerSecond(1.2)).toBeCloseTo(150000.0, 1);
    expect(DataTransferRate.GigaBitsPerSecond.toKiloBytesPerSecond(0.9)).toBeCloseTo(112500.0, 1);
    expect(DataTransferRate.GigaBitsPerSecond.toKiloBytesPerSecond(0.001)).toBeCloseTo(125.0, 1);
});

it('From GigaBits Per Second to MegaBytes Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.GigaBitsPerSecond.toMegaBytesPerSecond(value)
            const convertBack = DataTransferRate.MegaBytesPerSecond.toGigaBitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known GigaBits Per Second to MegaBytes Per Second', () => {
    expect(DataTransferRate.GigaBitsPerSecond.toMegaBytesPerSecond(0.9)).toBeCloseTo(112.5, 1);
    expect(DataTransferRate.GigaBitsPerSecond.toMegaBytesPerSecond(1.2)).toBeCloseTo(150.0, 1);
    expect(DataTransferRate.GigaBitsPerSecond.toMegaBytesPerSecond(80.1)).toBeCloseTo(10012.5, 1);
});

it('From GigaBits Per Second to GigaBytes Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.GigaBitsPerSecond.toGigaBytesPerSecond(value)
            const convertBack = DataTransferRate.GigaBytesPerSecond.toGigaBitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known GigaBits Per Second to GigaBytes Per Second', () => {
    expect(DataTransferRate.GigaBitsPerSecond.toGigaBytesPerSecond(99.0)).toBeCloseTo(12.375, 1);
    expect(DataTransferRate.GigaBitsPerSecond.toGigaBytesPerSecond(123.123)).toBeCloseTo(15.390375, 1);
    expect(DataTransferRate.GigaBitsPerSecond.toGigaBytesPerSecond(8000.9)).toBeCloseTo(1000.1125, 1);
});

it('From GigaBits Per Second to TeraBytes Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.GigaBitsPerSecond.toTeraBytesPerSecond(value)
            const convertBack = DataTransferRate.TeraBytesPerSecond.toGigaBitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known GigaBits Per Second to TeraBytes Per Second', () => {
    expect(DataTransferRate.GigaBitsPerSecond.toTeraBytesPerSecond(9000.0)).toBeCloseTo(1.125, 1);
    expect(DataTransferRate.GigaBitsPerSecond.toTeraBytesPerSecond(1234567.0)).toBeCloseTo(154.320875, 1);
    expect(DataTransferRate.GigaBitsPerSecond.toTeraBytesPerSecond(613.0)).toBeCloseTo(0.076625, 1);
});

it('From GigaBits Per Second to Kibibits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.GigaBitsPerSecond.toKibibitsPerSecond(value)
            const convertBack = DataTransferRate.KibibitsPerSecond.toGigaBitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known GigaBits Per Second to Kibibits Per Second', () => {
    expect(DataTransferRate.GigaBitsPerSecond.toKibibitsPerSecond(0.8)).toBeCloseTo(781250.0, 1);
    expect(DataTransferRate.GigaBitsPerSecond.toKibibitsPerSecond(0.012)).toBeCloseTo(11718.75, 1);
    expect(DataTransferRate.GigaBitsPerSecond.toKibibitsPerSecond(0.002)).toBeCloseTo(1953.125, 1);
});

it('From GigaBits Per Second to Mebibits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.GigaBitsPerSecond.toMebibitsPerSecond(value)
            const convertBack = DataTransferRate.MebibitsPerSecond.toGigaBitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known GigaBits Per Second to Mebibits Per Second', () => {
    expect(DataTransferRate.GigaBitsPerSecond.toMebibitsPerSecond(0.002)).toBeCloseTo(1.9073486, 1);
    expect(DataTransferRate.GigaBitsPerSecond.toMebibitsPerSecond(0.9)).toBeCloseTo(858.6, 1);
    expect(DataTransferRate.GigaBitsPerSecond.toMebibitsPerSecond(6.1)).toBeCloseTo(5819.4, 1);
});

it('From GigaBytes Per Second to Bits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.GigaBytesPerSecond.toBitsPerSecond(value)
            const convertBack = DataTransferRate.BitsPerSecond.toGigaBytesPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known GigaBytes Per Second to Bits Per Second', () => {
    expect(DataTransferRate.GigaBytesPerSecond.toBitsPerSecond(0.004)).toBeCloseTo(32000000.0, 1);
    expect(DataTransferRate.GigaBytesPerSecond.toBitsPerSecond(0.012)).toBeCloseTo(96000000, 1);
    expect(DataTransferRate.GigaBytesPerSecond.toBitsPerSecond(3e-9)).toBeCloseTo(24.0, 1);
});

it('From GigaBytes Per Second to KiloBits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.GigaBytesPerSecond.toKiloBitsPerSecond(value)
            const convertBack = DataTransferRate.KiloBitsPerSecond.toGigaBytesPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known GigaBytes Per Second to KiloBits Per Second', () => {
    expect(DataTransferRate.GigaBytesPerSecond.toKiloBitsPerSecond(0.009)).toBeCloseTo(72000.0, 1);
    expect(DataTransferRate.GigaBytesPerSecond.toKiloBitsPerSecond(1.2e-4)).toBeCloseTo(960.0, 1);
    expect(DataTransferRate.GigaBytesPerSecond.toKiloBitsPerSecond(0.0078)).toBeCloseTo(62400.0, 1);
});

it('From GigaBytes Per Second to MegaBits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.GigaBytesPerSecond.toMegaBitsPerSecond(value)
            const convertBack = DataTransferRate.MegaBitsPerSecond.toGigaBytesPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known GigaBytes Per Second to MegaBits Per Second', () => {
    expect(DataTransferRate.GigaBytesPerSecond.toMegaBitsPerSecond(0.0078)).toBeCloseTo(62.4, 1);
    expect(DataTransferRate.GigaBytesPerSecond.toMegaBitsPerSecond(0.01)).toBeCloseTo(80.0, 1);
    expect(DataTransferRate.GigaBytesPerSecond.toMegaBitsPerSecond(0.001234)).toBeCloseTo(9.872, 1);
});

it('From GigaBytes Per Second to GigaBits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.GigaBytesPerSecond.toGigaBitsPerSecond(value)
            const convertBack = DataTransferRate.GigaBitsPerSecond.toGigaBytesPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known GigaBytes Per Second to GigaBits Per Second', () => {
    expect(DataTransferRate.GigaBytesPerSecond.toGigaBitsPerSecond(5.0)).toBeCloseTo(40.0, 1);
    expect(DataTransferRate.GigaBytesPerSecond.toGigaBitsPerSecond(1.2)).toBeCloseTo(9.6, 1);
    expect(DataTransferRate.GigaBytesPerSecond.toGigaBitsPerSecond(0.01)).toBeCloseTo(0.08, 1);
});

it('From GigaBytes Per Second to TeraBits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.GigaBytesPerSecond.toTeraBitsPerSecond(value)
            const convertBack = DataTransferRate.TeraBitsPerSecond.toGigaBytesPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known GigaBytes Per Second to TeraBits Per Second', () => {
    expect(DataTransferRate.GigaBytesPerSecond.toTeraBitsPerSecond(70.0)).toBeCloseTo(0.56, 1);
    expect(DataTransferRate.GigaBytesPerSecond.toTeraBitsPerSecond(9001.0)).toBeCloseTo(72.008, 1);
    expect(DataTransferRate.GigaBytesPerSecond.toTeraBitsPerSecond(768123.9)).toBeCloseTo(6144.9912, 1);
});

it('From GigaBytes Per Second to KiloBytes Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.GigaBytesPerSecond.toKiloBytesPerSecond(value)
            const convertBack = DataTransferRate.KiloBytesPerSecond.toGigaBytesPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known GigaBytes Per Second to KiloBytes Per Second', () => {
    expect(DataTransferRate.GigaBytesPerSecond.toKiloBytesPerSecond(0.2)).toBeCloseTo(200000.0, 1);
    expect(DataTransferRate.GigaBytesPerSecond.toKiloBytesPerSecond(0.009)).toBeCloseTo(9000.0, 1);
    expect(DataTransferRate.GigaBytesPerSecond.toKiloBytesPerSecond(0.00123)).toBeCloseTo(1230.0, 1);
});

it('From GigaBytes Per Second to MegaBytes Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.GigaBytesPerSecond.toMegaBytesPerSecond(value)
            const convertBack = DataTransferRate.MegaBytesPerSecond.toGigaBytesPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known GigaBytes Per Second to MegaBytes Per Second', () => {
    expect(DataTransferRate.GigaBytesPerSecond.toMegaBytesPerSecond(0.9)).toBeCloseTo(900.0, 1);
    expect(DataTransferRate.GigaBytesPerSecond.toMegaBytesPerSecond(12.0)).toBeCloseTo(12000.0, 1);
    expect(DataTransferRate.GigaBytesPerSecond.toMegaBytesPerSecond(35.6)).toBeCloseTo(35600.0, 1);
});

it('From GigaBytes Per Second to TeraBytes Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.GigaBytesPerSecond.toTeraBytesPerSecond(value)
            const convertBack = DataTransferRate.TeraBytesPerSecond.toGigaBytesPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known GigaBytes Per Second to TeraBytes Per Second', () => {
    expect(DataTransferRate.GigaBytesPerSecond.toTeraBytesPerSecond(35.6)).toBeCloseTo(0.0356, 1);
    expect(DataTransferRate.GigaBytesPerSecond.toTeraBytesPerSecond(100.23)).toBeCloseTo(0.10023, 1);
    expect(DataTransferRate.GigaBytesPerSecond.toTeraBytesPerSecond(900100.0)).toBeCloseTo(900.1, 1);
});

it('From GigaBytes Per Second to Kibibits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.GigaBytesPerSecond.toKibibitsPerSecond(value)
            const convertBack = DataTransferRate.KibibitsPerSecond.toGigaBytesPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known GigaBytes Per Second to Kibibits Per Second', () => {
    expect(DataTransferRate.GigaBytesPerSecond.toKibibitsPerSecond(0.05)).toBeCloseTo(390625.0, 1);
    expect(DataTransferRate.GigaBytesPerSecond.toKibibitsPerSecond(0.008)).toBeCloseTo(62500.0, 1);
    expect(DataTransferRate.GigaBytesPerSecond.toKibibitsPerSecond(0.00123)).toBeCloseTo(9609.375, 1);
});

it('From GigaBytes Per Second to Mebibits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.GigaBytesPerSecond.toMebibitsPerSecond(value)
            const convertBack = DataTransferRate.MebibitsPerSecond.toGigaBytesPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known GigaBytes Per Second to Mebibits Per Second', () => {
    expect(DataTransferRate.GigaBytesPerSecond.toMebibitsPerSecond(0.009)).toBeCloseTo(68.66451, 1);
    expect(DataTransferRate.GigaBytesPerSecond.toMebibitsPerSecond(1.2)).toBeCloseTo(9155.268, 1);
    expect(DataTransferRate.GigaBytesPerSecond.toMebibitsPerSecond(19.2)).toBeCloseTo(146484.288, 1);
});

it('From Kibibits Per Second to Bits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.KibibitsPerSecond.toBitsPerSecond(value)
            const convertBack = DataTransferRate.BitsPerSecond.toKibibitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Kibibits Per Second to Bits Per Second', () => {
    expect(DataTransferRate.KibibitsPerSecond.toBitsPerSecond(2.0)).toBeCloseTo(2048.0, 1);
    expect(DataTransferRate.KibibitsPerSecond.toBitsPerSecond(9.0)).toBeCloseTo(9216.0, 1);
    expect(DataTransferRate.KibibitsPerSecond.toBitsPerSecond(17.8)).toBeCloseTo(18227.2, 1);
});

it('From Kibibits Per Second to KiloBits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.KibibitsPerSecond.toKiloBitsPerSecond(value)
            const convertBack = DataTransferRate.KiloBitsPerSecond.toKibibitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Kibibits Per Second to KiloBits Per Second', () => {
    expect(DataTransferRate.KibibitsPerSecond.toKiloBitsPerSecond(6.2)).toBeCloseTo(6.3488, 1);
    expect(DataTransferRate.KibibitsPerSecond.toKiloBitsPerSecond(0.9)).toBeCloseTo(0.9216, 1);
    expect(DataTransferRate.KibibitsPerSecond.toKiloBitsPerSecond(87.0)).toBeCloseTo(89.088, 1);
});

it('From Kibibits Per Second to MegaBits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.KibibitsPerSecond.toMegaBitsPerSecond(value)
            const convertBack = DataTransferRate.MegaBitsPerSecond.toKibibitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Kibibits Per Second to MegaBits Per Second', () => {
    expect(DataTransferRate.KibibitsPerSecond.toMegaBitsPerSecond(87.0)).toBeCloseTo(0.089088, 1);
    expect(DataTransferRate.KibibitsPerSecond.toMegaBitsPerSecond(12.34)).toBeCloseTo(0.01263616, 1);
    expect(DataTransferRate.KibibitsPerSecond.toMegaBitsPerSecond(123456.0)).toBeCloseTo(126.418879, 1);
});

it('From Kibibits Per Second to GigaBits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.KibibitsPerSecond.toGigaBitsPerSecond(value)
            const convertBack = DataTransferRate.GigaBitsPerSecond.toKibibitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Kibibits Per Second to GigaBits Per Second', () => {
    expect(DataTransferRate.KibibitsPerSecond.toGigaBitsPerSecond(123456.0)).toBeCloseTo(0.126418944, 1);
    expect(DataTransferRate.KibibitsPerSecond.toGigaBitsPerSecond(8000000.0)).toBeCloseTo(8.192, 1);
    expect(DataTransferRate.KibibitsPerSecond.toGigaBitsPerSecond(1276876)).toBeCloseTo(1.307521024, 1);
});

it('From Kibibits Per Second to TeraBits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.KibibitsPerSecond.toTeraBitsPerSecond(value)
            const convertBack = DataTransferRate.TeraBitsPerSecond.toKibibitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Kibibits Per Second to TeraBits Per Second', () => {
    expect(DataTransferRate.KibibitsPerSecond.toTeraBitsPerSecond(800000000.0)).toBeCloseTo(0.8192, 1);
    expect(DataTransferRate.KibibitsPerSecond.toTeraBitsPerSecond(1.5e12)).toBeCloseTo(1536.0, 1);
    expect(DataTransferRate.KibibitsPerSecond.toTeraBitsPerSecond(9999999.0)).toBeCloseTo(0.01023999898, 1);
});

it('From Kibibits Per Second to KiloBytes Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.KibibitsPerSecond.toKiloBytesPerSecond(value)
            const convertBack = DataTransferRate.KiloBytesPerSecond.toKibibitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Kibibits Per Second to KiloBytes Per Second', () => {
    expect(DataTransferRate.KibibitsPerSecond.toKiloBytesPerSecond(919.0)).toBeCloseTo(117.632, 1);
    expect(DataTransferRate.KibibitsPerSecond.toKiloBytesPerSecond(77.4)).toBeCloseTo(9.9072, 1);
    expect(DataTransferRate.KibibitsPerSecond.toKiloBytesPerSecond(109.109)).toBeCloseTo(13.965952, 1);
});

it('From Kibibits Per Second to MegaBytes Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.KibibitsPerSecond.toMegaBytesPerSecond(value)
            const convertBack = DataTransferRate.MegaBytesPerSecond.toKibibitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Kibibits Per Second to MegaBytes Per Second', () => {
    expect(DataTransferRate.KibibitsPerSecond.toMegaBytesPerSecond(1000.0)).toBeCloseTo(0.128, 1);
    expect(DataTransferRate.KibibitsPerSecond.toMegaBytesPerSecond(800.123)).toBeCloseTo(0.102415744, 1);
    expect(DataTransferRate.KibibitsPerSecond.toMegaBytesPerSecond(123456.0)).toBeCloseTo(15.802368, 1);
});

it('From Kibibits Per Second to GigaBytes Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.KibibitsPerSecond.toGigaBytesPerSecond(value)
            const convertBack = DataTransferRate.GigaBytesPerSecond.toKibibitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Kibibits Per Second to GigaBytes Per Second', () => {
    expect(DataTransferRate.KibibitsPerSecond.toGigaBytesPerSecond(12345678.0)).toBeCloseTo(1.580347926, 1);
    expect(DataTransferRate.KibibitsPerSecond.toGigaBytesPerSecond(8e12)).toBeCloseTo(1024000.00, 1);
    expect(DataTransferRate.KibibitsPerSecond.toGigaBytesPerSecond(1.2e5)).toBeCloseTo(0.01536, 1);
});

it('From Kibibits Per Second to TeraBytes Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.KibibitsPerSecond.toTeraBytesPerSecond(value)
            const convertBack = DataTransferRate.TeraBytesPerSecond.toKibibitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Kibibits Per Second to TeraBytes Per Second', () => {
    expect(DataTransferRate.KibibitsPerSecond.toTeraBytesPerSecond(120000000.0)).toBeCloseTo(0.01536, 1);
    expect(DataTransferRate.KibibitsPerSecond.toTeraBytesPerSecond(88e12)).toBeCloseTo(11264.0, 1);
    expect(DataTransferRate.KibibitsPerSecond.toTeraBytesPerSecond(9000000.0)).toBeCloseTo(0.009216, 1);
});

it('From Kibibits Per Second to Mebibits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.KibibitsPerSecond.toMebibitsPerSecond(value)
            const convertBack = DataTransferRate.MebibitsPerSecond.toKibibitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Kibibits Per Second to Mebibits Per Second', () => {
    expect(DataTransferRate.KibibitsPerSecond.toMebibitsPerSecond(600.0)).toBeCloseTo(0.5859375, 1);
    expect(DataTransferRate.KibibitsPerSecond.toMebibitsPerSecond(12345.0)).toBeCloseTo(12.055664, 1);
    expect(DataTransferRate.KibibitsPerSecond.toMebibitsPerSecond(101.0)).toBeCloseTo(0.0986328, 1);
});

it('From KiloBits Per Second to Bits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.KiloBitsPerSecond.toBitsPerSecond(value)
            const convertBack = DataTransferRate.BitsPerSecond.toKiloBitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known KiloBits Per Second to Bits Per Second', () => {
    expect(DataTransferRate.KiloBitsPerSecond.toBitsPerSecond(9.0)).toBeCloseTo(9000.0, 1);
    expect(DataTransferRate.KiloBitsPerSecond.toBitsPerSecond(6.7)).toBeCloseTo(6700.0, 1);
    expect(DataTransferRate.KiloBitsPerSecond.toBitsPerSecond(1.2345)).toBeCloseTo(1234.5, 1);
});

it('From KiloBits Per Second to MegaBits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.KiloBitsPerSecond.toMegaBitsPerSecond(value)
            const convertBack = DataTransferRate.MegaBitsPerSecond.toKiloBitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known KiloBits Per Second to MegaBits Per Second', () => {
    expect(DataTransferRate.KiloBitsPerSecond.toMegaBitsPerSecond(900.0)).toBeCloseTo(0.9, 1);
    expect(DataTransferRate.KiloBitsPerSecond.toMegaBitsPerSecond(12345.0)).toBeCloseTo(12.345, 1);
    expect(DataTransferRate.KiloBitsPerSecond.toMegaBitsPerSecond(9988.0)).toBeCloseTo(9.988, 1);
});

it('From KiloBits Per Second to GigaBits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.KiloBitsPerSecond.toGigaBitsPerSecond(value)
            const convertBack = DataTransferRate.GigaBitsPerSecond.toKiloBitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known KiloBits Per Second to GigaBits Per Second', () => {
    expect(DataTransferRate.KiloBitsPerSecond.toGigaBitsPerSecond(123456.0)).toBeCloseTo(0.123456, 1);
    expect(DataTransferRate.KiloBitsPerSecond.toGigaBitsPerSecond(8000700.0)).toBeCloseTo(8.0007, 1);
    expect(DataTransferRate.KiloBitsPerSecond.toGigaBitsPerSecond(191987578.0)).toBeCloseTo(191.987578, 1);
});

it('From KiloBits Per Second to TeraBits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.KiloBitsPerSecond.toTeraBitsPerSecond(value)
            const convertBack = DataTransferRate.TeraBitsPerSecond.toKiloBitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known KiloBits Per Second to TeraBits Per Second', () => {
    expect(DataTransferRate.KiloBitsPerSecond.toTeraBitsPerSecond(191987578)).toBeCloseTo(0.191987578, 1);
    expect(DataTransferRate.KiloBitsPerSecond.toTeraBitsPerSecond(9010081903.0)).toBeCloseTo(9.010081903, 1);
    expect(DataTransferRate.KiloBitsPerSecond.toTeraBitsPerSecond(123456789.0)).toBeCloseTo(0.123456789, 1);
});

it('From KiloBits Per Second to KiloBytes Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.KiloBitsPerSecond.toKiloBytesPerSecond(value)
            const convertBack = DataTransferRate.KiloBytesPerSecond.toKiloBitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known KiloBits Per Second to KiloBytes Per Second', () => {
    expect(DataTransferRate.KiloBitsPerSecond.toKiloBytesPerSecond(80.0)).toBeCloseTo(10.0, 1);
    expect(DataTransferRate.KiloBitsPerSecond.toKiloBytesPerSecond(15.67)).toBeCloseTo(1.95875, 1);
    expect(DataTransferRate.KiloBitsPerSecond.toKiloBytesPerSecond(8007.09)).toBeCloseTo(1000.88625, 1);
});

it('From KiloBits Per Second to MegaBytes Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.KiloBitsPerSecond.toMegaBytesPerSecond(value)
            const convertBack = DataTransferRate.MegaBytesPerSecond.toKiloBitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known KiloBits Per Second to MegaBytes Per Second', () => {
    expect(DataTransferRate.KiloBitsPerSecond.toMegaBytesPerSecond(123456.0)).toBeCloseTo(15.432, 1);
    expect(DataTransferRate.KiloBitsPerSecond.toMegaBytesPerSecond(998877.0)).toBeCloseTo(124.859625, 1);
    expect(DataTransferRate.KiloBitsPerSecond.toMegaBytesPerSecond(10090.0)).toBeCloseTo(1.26125, 1);
});

it('From KiloBits Per Second to GigaBytes Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.KiloBitsPerSecond.toGigaBytesPerSecond(value)
            const convertBack = DataTransferRate.GigaBytesPerSecond.toKiloBitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known KiloBits Per Second to GigaBytes Per Second', () => {
    expect(DataTransferRate.KiloBitsPerSecond.toGigaBytesPerSecond(1828972.0)).toBeCloseTo(0.2286215, 1);
    expect(DataTransferRate.KiloBitsPerSecond.toGigaBytesPerSecond(879860.8)).toBeCloseTo(0.1099826, 1);
    expect(DataTransferRate.KiloBitsPerSecond.toGigaBytesPerSecond(78178971.0)).toBeCloseTo(9.772371375, 1);
});

it('From KiloBits Per Second to TeraBytes Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.KiloBitsPerSecond.toTeraBytesPerSecond(value)
            const convertBack = DataTransferRate.TeraBytesPerSecond.toKiloBitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known KiloBits Per Second to TeraBytes Per Second', () => {
    expect(DataTransferRate.KiloBitsPerSecond.toTeraBytesPerSecond(1234567891.0)).toBeCloseTo(0.154320986375, 1);
    expect(DataTransferRate.KiloBitsPerSecond.toTeraBytesPerSecond(999999098.0)).toBeCloseTo(0.12499988725, 1);
    expect(DataTransferRate.KiloBitsPerSecond.toTeraBytesPerSecond(84618364142.0)).toBeCloseTo(10.57729551775, 1);
});

it('From KiloBits Per Second to Kibibits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.KiloBitsPerSecond.toKibibitsPerSecond(value)
            const convertBack = DataTransferRate.KibibitsPerSecond.toKiloBitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known KiloBits Per Second to Kibibits Per Second', () => {
    expect(DataTransferRate.KiloBitsPerSecond.toKibibitsPerSecond(89.1)).toBeCloseTo(87.01172, 1);
    expect(DataTransferRate.KiloBitsPerSecond.toKibibitsPerSecond(7.1)).toBeCloseTo(6.93359, 1);
    expect(DataTransferRate.KiloBitsPerSecond.toKibibitsPerSecond(438.0)).toBeCloseTo(427.734, 1);
});

it('From KiloBits Per Second to Mebibits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.KiloBitsPerSecond.toMebibitsPerSecond(value)
            const convertBack = DataTransferRate.MebibitsPerSecond.toKiloBitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known KiloBits Per Second to Mebibits Per Second', () => {
    expect(DataTransferRate.KiloBitsPerSecond.toMebibitsPerSecond(77790.0)).toBeCloseTo(74.186325, 1);
    expect(DataTransferRate.KiloBitsPerSecond.toMebibitsPerSecond(123456.0)).toBeCloseTo(117.736816, 1);
    expect(DataTransferRate.KiloBitsPerSecond.toMebibitsPerSecond(23972.0)).toBeCloseTo(22.861481, 1);
});

it('From KiloBytes Per Second to Bits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.KiloBytesPerSecond.toBitsPerSecond(value)
            const convertBack = DataTransferRate.BitsPerSecond.toKiloBytesPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known KiloBytes Per Second to Bits Per Second', () => {
    expect(DataTransferRate.KiloBytesPerSecond.toBitsPerSecond(123.456)).toBeCloseTo(987648.0, 1);
    expect(DataTransferRate.KiloBytesPerSecond.toBitsPerSecond(900.0)).toBeCloseTo(7.2e+6, 1);
    expect(DataTransferRate.KiloBytesPerSecond.toBitsPerSecond(100200.0)).toBeCloseTo(801600000, 1);
});

it('From KiloBytes Per Second to KiloBits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.KiloBytesPerSecond.toKiloBitsPerSecond(value)
            const convertBack = DataTransferRate.KiloBitsPerSecond.toKiloBytesPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known KiloBytes Per Second to KiloBits Per Second', () => {
    expect(DataTransferRate.KiloBytesPerSecond.toKiloBitsPerSecond(4.0)).toBeCloseTo(32.0, 1);
    expect(DataTransferRate.KiloBytesPerSecond.toKiloBitsPerSecond(1.2)).toBeCloseTo(9.6, 1);
    expect(DataTransferRate.KiloBytesPerSecond.toKiloBitsPerSecond(88.1)).toBeCloseTo(704.8, 1);
});

it('From KiloBytes Per Second to MegaBits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.KiloBytesPerSecond.toMegaBitsPerSecond(value)
            const convertBack = DataTransferRate.MegaBitsPerSecond.toKiloBytesPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known KiloBytes Per Second to MegaBits Per Second', () => {
    expect(DataTransferRate.KiloBytesPerSecond.toMegaBitsPerSecond(88.1)).toBeCloseTo(0.7048, 1);
    expect(DataTransferRate.KiloBytesPerSecond.toMegaBitsPerSecond(7.1)).toBeCloseTo(0.0568, 1);
    expect(DataTransferRate.KiloBytesPerSecond.toMegaBitsPerSecond(12.8)).toBeCloseTo(0.1024, 1);
});

it('From KiloBytes Per Second to GigaBits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.KiloBytesPerSecond.toGigaBitsPerSecond(value)
            const convertBack = DataTransferRate.GigaBitsPerSecond.toKiloBytesPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known KiloBytes Per Second to GigaBits Per Second', () => {
    expect(DataTransferRate.KiloBytesPerSecond.toGigaBitsPerSecond(10080.0)).toBeCloseTo(0.08064, 1);
    expect(DataTransferRate.KiloBytesPerSecond.toGigaBitsPerSecond(4.5e+9)).toBeCloseTo(36000.0, 1);
    expect(DataTransferRate.KiloBytesPerSecond.toGigaBitsPerSecond(271279.0)).toBeCloseTo(2.170232, 1);
});

it('From KiloBytes Per Second to TeraBits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.KiloBytesPerSecond.toTeraBitsPerSecond(value)
            const convertBack = DataTransferRate.TeraBitsPerSecond.toKiloBytesPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known KiloBytes Per Second to TeraBits Per Second', () => {
    expect(DataTransferRate.KiloBytesPerSecond.toTeraBitsPerSecond(9009000.0)).toBeCloseTo(0.072072, 1);
    expect(DataTransferRate.KiloBytesPerSecond.toTeraBitsPerSecond(7.2e9)).toBeCloseTo(57.6, 1);
    expect(DataTransferRate.KiloBytesPerSecond.toTeraBitsPerSecond(100100100900.0)).toBeCloseTo(800.8008072, 1);
});

it('From KiloBytes Per Second to MegaBytes Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.KiloBytesPerSecond.toMegaBytesPerSecond(value)
            const convertBack = DataTransferRate.MegaBytesPerSecond.toKiloBytesPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known KiloBytes Per Second to MegaBytes Per Second', () => {
    expect(DataTransferRate.KiloBytesPerSecond.toMegaBytesPerSecond(1009.0)).toBeCloseTo(1.009, 1);
    expect(DataTransferRate.KiloBytesPerSecond.toMegaBytesPerSecond(8899.0)).toBeCloseTo(8.899, 1);
    expect(DataTransferRate.KiloBytesPerSecond.toMegaBytesPerSecond(619.0)).toBeCloseTo(0.619, 1);
});

it('From KiloBytes Per Second to GigaBytes Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.KiloBytesPerSecond.toGigaBytesPerSecond(value)
            const convertBack = DataTransferRate.GigaBytesPerSecond.toKiloBytesPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known KiloBytes Per Second to GigaBytes Per Second', () => {
    expect(DataTransferRate.KiloBytesPerSecond.toGigaBytesPerSecond(900800.0)).toBeCloseTo(0.9008, 1);
    expect(DataTransferRate.KiloBytesPerSecond.toGigaBytesPerSecond(1234567.0)).toBeCloseTo(1.234567, 1);
    expect(DataTransferRate.KiloBytesPerSecond.toGigaBytesPerSecond(7.9e9)).toBeCloseTo(7900.0, 1);
});

it('From KiloBytes Per Second to TeraBytes Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.KiloBytesPerSecond.toTeraBytesPerSecond(value)
            const convertBack = DataTransferRate.TeraBytesPerSecond.toKiloBytesPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known KiloBytes Per Second to TeraBytes Per Second', () => {
    expect(DataTransferRate.KiloBytesPerSecond.toTeraBytesPerSecond(0.9)).toBeCloseTo(9e-10, 1);
    expect(DataTransferRate.KiloBytesPerSecond.toTeraBytesPerSecond(140000000)).toBeCloseTo(0.14, 1);
    expect(DataTransferRate.KiloBytesPerSecond.toTeraBytesPerSecond(7.0)).toBeCloseTo(7e-9, 1);
});

it('From KiloBytes Per Second to Kibibits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.KiloBytesPerSecond.toKibibitsPerSecond(value)
            const convertBack = DataTransferRate.KibibitsPerSecond.toKiloBytesPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known KiloBytes Per Second to Kibibits Per Second', () => {
    expect(DataTransferRate.KiloBytesPerSecond.toKibibitsPerSecond(0.009)).toBeCloseTo(0.0703125, 1);
    expect(DataTransferRate.KiloBytesPerSecond.toKibibitsPerSecond(6e+3)).toBeCloseTo(46872.0, 1);
    expect(DataTransferRate.KiloBytesPerSecond.toKibibitsPerSecond(1.23)).toBeCloseTo(9.609375, 1);
});

it('From KiloBytes Per Second to Mebibits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.KiloBytesPerSecond.toMebibitsPerSecond(value)
            const convertBack = DataTransferRate.MebibitsPerSecond.toKiloBytesPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known KiloBytes Per Second to Mebibits Per Second', () => {
    expect(DataTransferRate.KiloBytesPerSecond.toMebibitsPerSecond(70.0)).toBeCloseTo(0.534058, 1);
    expect(DataTransferRate.KiloBytesPerSecond.toMebibitsPerSecond(9.0)).toBeCloseTo(0.0686646, 1);
    expect(DataTransferRate.KiloBytesPerSecond.toMebibitsPerSecond(10022.0)).toBeCloseTo(76.461792, 1);
});

it('From Mebibits Per Second to Bits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.MebibitsPerSecond.toBitsPerSecond(value)
            const convertBack = DataTransferRate.BitsPerSecond.toMebibitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Mebibits Per Second to Bits Per Second', () => {
    expect(DataTransferRate.MebibitsPerSecond.toBitsPerSecond(0.9)).toBeCloseTo(943718.4, 1);
    expect(DataTransferRate.MebibitsPerSecond.toBitsPerSecond(0.006)).toBeCloseTo(6291.456, 1);
    expect(DataTransferRate.MebibitsPerSecond.toBitsPerSecond(2.0)).toBeCloseTo(2097152.0, 1);
});

it('From Mebibits Per Second to KiloBits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.MebibitsPerSecond.toKiloBitsPerSecond(value)
            const convertBack = DataTransferRate.KiloBitsPerSecond.toMebibitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Mebibits Per Second to KiloBits Per Second', () => {
    expect(DataTransferRate.MebibitsPerSecond.toKiloBitsPerSecond(0.8)).toBeCloseTo(838.861, 1);
    expect(DataTransferRate.MebibitsPerSecond.toKiloBitsPerSecond(2.0)).toBeCloseTo(2097.15, 1);
    expect(DataTransferRate.MebibitsPerSecond.toKiloBitsPerSecond(0.23)).toBeCloseTo(241.1725, 1);
});

it('From Mebibits Per Second to MegaBits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.MebibitsPerSecond.toMegaBitsPerSecond(value)
            const convertBack = DataTransferRate.MegaBitsPerSecond.toMebibitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Mebibits Per Second to MegaBits Per Second', () => {
    expect(DataTransferRate.MebibitsPerSecond.toMegaBitsPerSecond(0.9)).toBeCloseTo(0.943718, 1);
    expect(DataTransferRate.MebibitsPerSecond.toMegaBitsPerSecond(12.3)).toBeCloseTo(12.89748, 1);
    expect(DataTransferRate.MebibitsPerSecond.toMegaBitsPerSecond(8.1)).toBeCloseTo(8.49347, 1);
});

it('From Mebibits Per Second to GigaBits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.MebibitsPerSecond.toGigaBitsPerSecond(value)
            const convertBack = DataTransferRate.GigaBitsPerSecond.toMebibitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Mebibits Per Second to GigaBits Per Second', () => {
    expect(DataTransferRate.MebibitsPerSecond.toGigaBitsPerSecond(12345.0)).toBeCloseTo(12.944671, 1);
    expect(DataTransferRate.MebibitsPerSecond.toGigaBitsPerSecond(100.0)).toBeCloseTo(0.104858, 1);
    expect(DataTransferRate.MebibitsPerSecond.toGigaBitsPerSecond(999.9)).toBeCloseTo(1.0484711, 1);
});

it('From Mebibits Per Second to TeraBits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.MebibitsPerSecond.toTeraBitsPerSecond(value)
            const convertBack = DataTransferRate.TeraBitsPerSecond.toMebibitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Mebibits Per Second to TeraBits Per Second', () => {
    expect(DataTransferRate.MebibitsPerSecond.toTeraBitsPerSecond(100009.0)).toBeCloseTo(0.104867037, 1);
    expect(DataTransferRate.MebibitsPerSecond.toTeraBitsPerSecond(9876543.0)).toBeCloseTo(10.35630595, 1);
    expect(DataTransferRate.MebibitsPerSecond.toTeraBitsPerSecond(1000900.0)).toBeCloseTo(1.049519718, 1);
});

it('From Mebibits Per Second to KiloBytes Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.MebibitsPerSecond.toKiloBytesPerSecond(value)
            const convertBack = DataTransferRate.KiloBytesPerSecond.toMebibitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Mebibits Per Second to KiloBytes Per Second', () => {
    expect(DataTransferRate.MebibitsPerSecond.toKiloBytesPerSecond(4.0)).toBeCloseTo(524.288, 1);
    expect(DataTransferRate.MebibitsPerSecond.toKiloBytesPerSecond(1.45)).toBeCloseTo(190.0544, 1);
    expect(DataTransferRate.MebibitsPerSecond.toKiloBytesPerSecond(88.11)).toBeCloseTo(11548.754, 1);
});

it('From Mebibits Per Second to MegaBytes Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.MebibitsPerSecond.toMegaBytesPerSecond(value)
            const convertBack = DataTransferRate.MegaBytesPerSecond.toMebibitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Mebibits Per Second to MegaBytes Per Second', () => {
    expect(DataTransferRate.MebibitsPerSecond.toMegaBytesPerSecond(109.0)).toBeCloseTo(14.2868, 1);
    expect(DataTransferRate.MebibitsPerSecond.toMegaBytesPerSecond(55.67)).toBeCloseTo(7.2967782, 1);
    expect(DataTransferRate.MebibitsPerSecond.toMegaBytesPerSecond(45678.0)).toBeCloseTo(5987.1068, 1);
});

it('From Mebibits Per Second to GigaBytes Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.MebibitsPerSecond.toGigaBytesPerSecond(value)
            const convertBack = DataTransferRate.GigaBytesPerSecond.toMebibitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Mebibits Per Second to GigaBytes Per Second', () => {
    expect(DataTransferRate.MebibitsPerSecond.toGigaBytesPerSecond(4000.0)).toBeCloseTo(0.524288311, 1);
    expect(DataTransferRate.MebibitsPerSecond.toGigaBytesPerSecond(90100.0)).toBeCloseTo(11.80959421, 1);
    expect(DataTransferRate.MebibitsPerSecond.toGigaBytesPerSecond(1009.0)).toBeCloseTo(0.132251727, 1);
});

it('From Mebibits Per Second to TeraBytes Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.MebibitsPerSecond.toTeraBytesPerSecond(value)
            const convertBack = DataTransferRate.TeraBytesPerSecond.toMebibitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Mebibits Per Second to TeraBytes Per Second', () => {
    expect(DataTransferRate.MebibitsPerSecond.toTeraBytesPerSecond(1000009.0)).toBeCloseTo(0.1310731796, 1);
    expect(DataTransferRate.MebibitsPerSecond.toTeraBytesPerSecond(90808080.0)).toBeCloseTo(11.902396662, 1);
    expect(DataTransferRate.MebibitsPerSecond.toTeraBytesPerSecond(5.2e12)).toBeCloseTo(681574.4, 1);
});

it('From Mebibits Per Second to Kibibits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.MebibitsPerSecond.toKibibitsPerSecond(value)
            const convertBack = DataTransferRate.KibibitsPerSecond.toMebibitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Mebibits Per Second to Kibibits Per Second', () => {
    expect(DataTransferRate.MebibitsPerSecond.toKibibitsPerSecond(5.0)).toBeCloseTo(5120.0, 1);
    expect(DataTransferRate.MebibitsPerSecond.toKibibitsPerSecond(1234.56)).toBeCloseTo(1264189.44, 1);
    expect(DataTransferRate.MebibitsPerSecond.toKibibitsPerSecond(505.0)).toBeCloseTo(517120.0, 1);
});

it('From MegaBits Per Second to Bits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.MegaBitsPerSecond.toBitsPerSecond(value)
            const convertBack = DataTransferRate.BitsPerSecond.toMegaBitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known MegaBits Per Second to Bits Per Second', () => {
    expect(DataTransferRate.MegaBitsPerSecond.toBitsPerSecond(0.34)).toBeCloseTo(340000.0, 1);
    expect(DataTransferRate.MegaBitsPerSecond.toBitsPerSecond(9.12)).toBeCloseTo(9120000.0, 1);
    expect(DataTransferRate.MegaBitsPerSecond.toBitsPerSecond(0.987)).toBeCloseTo(987000.0, 1);
});

it('From MegaBits Per Second to KiloBits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.MegaBitsPerSecond.toKiloBitsPerSecond(value)
            const convertBack = DataTransferRate.KiloBitsPerSecond.toMegaBitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known MegaBits Per Second to KiloBits Per Second', () => {
    expect(DataTransferRate.MegaBitsPerSecond.toKiloBitsPerSecond(0.77)).toBeCloseTo(770.0, 1);
    expect(DataTransferRate.MegaBitsPerSecond.toKiloBitsPerSecond(5.0)).toBeCloseTo(5000.0, 1);
    expect(DataTransferRate.MegaBitsPerSecond.toKiloBitsPerSecond(0.987)).toBeCloseTo(987.0, 1);
});

it('From MegaBits Per Second to GigaBits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.MegaBitsPerSecond.toGigaBitsPerSecond(value)
            const convertBack = DataTransferRate.GigaBitsPerSecond.toMegaBitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known MegaBits Per Second to GigaBits Per Second', () => {
    expect(DataTransferRate.MegaBitsPerSecond.toGigaBitsPerSecond(900.0)).toBeCloseTo(0.9, 1);
    expect(DataTransferRate.MegaBitsPerSecond.toGigaBitsPerSecond(12345.0)).toBeCloseTo(12.345, 1);
    expect(DataTransferRate.MegaBitsPerSecond.toGigaBitsPerSecond(189.1)).toBeCloseTo(0.1891, 1);
});

it('From MegaBits Per Second to TeraBits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.MegaBitsPerSecond.toTeraBitsPerSecond(value)
            const convertBack = DataTransferRate.TeraBitsPerSecond.toMegaBitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known MegaBits Per Second to TeraBits Per Second', () => {
    expect(DataTransferRate.MegaBitsPerSecond.toTeraBitsPerSecond(100200300.0)).toBeCloseTo(100.2003, 1);
    expect(DataTransferRate.MegaBitsPerSecond.toTeraBitsPerSecond(99887777.0)).toBeCloseTo(99.887777, 1);
    expect(DataTransferRate.MegaBitsPerSecond.toTeraBitsPerSecond(80009.0)).toBeCloseTo(0.080009, 1);
});

it('From MegaBits Per Second to KiloBytes Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.MegaBitsPerSecond.toKiloBytesPerSecond(value)
            const convertBack = DataTransferRate.KiloBytesPerSecond.toMegaBitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known MegaBits Per Second to KiloBytes Per Second', () => {
    expect(DataTransferRate.MegaBitsPerSecond.toKiloBytesPerSecond(9.0)).toBeCloseTo(1125.0, 1);
    expect(DataTransferRate.MegaBitsPerSecond.toKiloBytesPerSecond(1.23)).toBeCloseTo(153.75, 1);
    expect(DataTransferRate.MegaBitsPerSecond.toKiloBytesPerSecond(98.1)).toBeCloseTo(12262.5, 1);
});

it('From MegaBits Per Second to MegaBytes Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.MegaBitsPerSecond.toMegaBytesPerSecond(value)
            const convertBack = DataTransferRate.MegaBytesPerSecond.toMegaBitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known MegaBits Per Second to MegaBytes Per Second', () => {
    expect(DataTransferRate.MegaBitsPerSecond.toMegaBytesPerSecond(98.1)).toBeCloseTo(12.2625, 1);
    expect(DataTransferRate.MegaBitsPerSecond.toMegaBytesPerSecond(10.9)).toBeCloseTo(1.3625, 1);
    expect(DataTransferRate.MegaBitsPerSecond.toMegaBytesPerSecond(888.123)).toBeCloseTo(111.015375, 1);
});

it('From MegaBits Per Second to GigaBytes Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.MegaBitsPerSecond.toGigaBytesPerSecond(value)
            const convertBack = DataTransferRate.GigaBytesPerSecond.toMegaBitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known MegaBits Per Second to GigaBytes Per Second', () => {
    expect(DataTransferRate.MegaBitsPerSecond.toGigaBytesPerSecond(900.0)).toBeCloseTo(0.1125, 1);
    expect(DataTransferRate.MegaBitsPerSecond.toGigaBytesPerSecond(10123.0)).toBeCloseTo(1.265375, 1);
    expect(DataTransferRate.MegaBitsPerSecond.toGigaBytesPerSecond(9988.0)).toBeCloseTo(1.2485, 1);
});

it('From MegaBits Per Second to TeraBytes Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.MegaBitsPerSecond.toTeraBytesPerSecond(value)
            const convertBack = DataTransferRate.TeraBytesPerSecond.toMegaBitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known MegaBits Per Second to TeraBytes Per Second', () => {
    expect(DataTransferRate.MegaBitsPerSecond.toTeraBytesPerSecond(998877.0)).toBeCloseTo(0.124859625, 1);
    expect(DataTransferRate.MegaBitsPerSecond.toTeraBytesPerSecond(100200400.0)).toBeCloseTo(12.5250375, 1);
    expect(DataTransferRate.MegaBitsPerSecond.toTeraBytesPerSecond(9008877.0)).toBeCloseTo(1.126109625, 1);
});

it('From MegaBits Per Second to Kibibits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.MegaBitsPerSecond.toKibibitsPerSecond(value)
            const convertBack = DataTransferRate.KibibitsPerSecond.toMegaBitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known MegaBits Per Second to Kibibits Per Second', () => {
    expect(DataTransferRate.MegaBitsPerSecond.toKibibitsPerSecond(12.0)).toBeCloseTo(11718.756, 1);
    expect(DataTransferRate.MegaBitsPerSecond.toKibibitsPerSecond(0.9)).toBeCloseTo(878.906, 1);
    expect(DataTransferRate.MegaBitsPerSecond.toKibibitsPerSecond(1.23)).toBeCloseTo(1201.172, 1);
});

it('From MegaBits Per Second to Mebibits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.MegaBitsPerSecond.toMebibitsPerSecond(value)
            const convertBack = DataTransferRate.MebibitsPerSecond.toMegaBitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known MegaBits Per Second to Mebibits Per Second', () => {
    expect(DataTransferRate.MegaBitsPerSecond.toMebibitsPerSecond(4.5)).toBeCloseTo(4.29153, 1);
    expect(DataTransferRate.MegaBitsPerSecond.toMebibitsPerSecond(0.8)).toBeCloseTo(0.762939, 1);
    expect(DataTransferRate.MegaBitsPerSecond.toMebibitsPerSecond(900.0)).toBeCloseTo(858.307, 1);
});

it('From MegaBytes Per Second to Bits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.MegaBytesPerSecond.toBitsPerSecond(value)
            const convertBack = DataTransferRate.BitsPerSecond.toMegaBytesPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known MegaBytes Per Second to Bits Per Second', () => {
    expect(DataTransferRate.MegaBytesPerSecond.toBitsPerSecond(0.04)).toBeCloseTo(320000.0, 1);
    expect(DataTransferRate.MegaBytesPerSecond.toBitsPerSecond(0.0091)).toBeCloseTo(72800.0, 1);
    expect(DataTransferRate.MegaBytesPerSecond.toBitsPerSecond(3e-5)).toBeCloseTo(240.0, 1);
});

it('From MegaBytes Per Second to KiloBits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.MegaBytesPerSecond.toKiloBitsPerSecond(value)
            const convertBack = DataTransferRate.KiloBitsPerSecond.toMegaBytesPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known MegaBytes Per Second to KiloBits Per Second', () => {
    expect(DataTransferRate.MegaBytesPerSecond.toKiloBitsPerSecond(6.0)).toBeCloseTo(48000.0, 1);
    expect(DataTransferRate.MegaBytesPerSecond.toKiloBitsPerSecond(0.3)).toBeCloseTo(2400.0, 1);
    expect(DataTransferRate.MegaBytesPerSecond.toKiloBitsPerSecond(0.009)).toBeCloseTo(72.0, 1);
});

it('From MegaBytes Per Second to MegaBits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.MegaBytesPerSecond.toMegaBitsPerSecond(value)
            const convertBack = DataTransferRate.MegaBitsPerSecond.toMegaBytesPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known MegaBytes Per Second to MegaBits Per Second', () => {
    expect(DataTransferRate.MegaBytesPerSecond.toMegaBitsPerSecond(3.0)).toBeCloseTo(24.0, 1);
    expect(DataTransferRate.MegaBytesPerSecond.toMegaBitsPerSecond(0.9)).toBeCloseTo(7.2, 1);
    expect(DataTransferRate.MegaBytesPerSecond.toMegaBitsPerSecond(13.0)).toBeCloseTo(104.0, 1);
});

it('From MegaBytes Per Second to GigaBits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.MegaBytesPerSecond.toGigaBitsPerSecond(value)
            const convertBack = DataTransferRate.GigaBitsPerSecond.toMegaBytesPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known MegaBytes Per Second to GigaBits Per Second', () => {
    expect(DataTransferRate.MegaBytesPerSecond.toGigaBitsPerSecond(13.0)).toBeCloseTo(0.104, 1);
    expect(DataTransferRate.MegaBytesPerSecond.toGigaBitsPerSecond(900.0)).toBeCloseTo(7.2, 1);
    expect(DataTransferRate.MegaBytesPerSecond.toGigaBitsPerSecond(18000.0)).toBeCloseTo(144.0, 1);
});

it('From MegaBytes Per Second to TeraBits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.MegaBytesPerSecond.toTeraBitsPerSecond(value)
            const convertBack = DataTransferRate.TeraBitsPerSecond.toMegaBytesPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known MegaBytes Per Second to TeraBits Per Second', () => {
    expect(DataTransferRate.MegaBytesPerSecond.toTeraBitsPerSecond(18000.0)).toBeCloseTo(0.144, 1);
    expect(DataTransferRate.MegaBytesPerSecond.toTeraBitsPerSecond(9718290.0)).toBeCloseTo(77.74632, 1);
    expect(DataTransferRate.MegaBytesPerSecond.toTeraBitsPerSecond(9e12)).toBeCloseTo(72000000.0, 1);
});

it('From MegaBytes Per Second to KiloBytes Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.MegaBytesPerSecond.toKiloBytesPerSecond(value)
            const convertBack = DataTransferRate.KiloBytesPerSecond.toMegaBytesPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known MegaBytes Per Second to KiloBytes Per Second', () => {
    expect(DataTransferRate.MegaBytesPerSecond.toKiloBytesPerSecond(6.0)).toBeCloseTo(6000.0, 1);
    expect(DataTransferRate.MegaBytesPerSecond.toKiloBytesPerSecond(0.9)).toBeCloseTo(900.0, 1);
    expect(DataTransferRate.MegaBytesPerSecond.toKiloBytesPerSecond(123.4)).toBeCloseTo(123400.0, 1);
});

it('From MegaBytes Per Second to GigaBytes Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.MegaBytesPerSecond.toGigaBytesPerSecond(value)
            const convertBack = DataTransferRate.GigaBytesPerSecond.toMegaBytesPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known MegaBytes Per Second to GigaBytes Per Second', () => {
    expect(DataTransferRate.MegaBytesPerSecond.toGigaBytesPerSecond(123.4)).toBeCloseTo(0.1234, 1);
    expect(DataTransferRate.MegaBytesPerSecond.toGigaBytesPerSecond(900.0)).toBeCloseTo(0.9, 1);
    expect(DataTransferRate.MegaBytesPerSecond.toGigaBytesPerSecond(8e6)).toBeCloseTo(8000.0, 1);
});

it('From MegaBytes Per Second to TeraBytes Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.MegaBytesPerSecond.toTeraBytesPerSecond(value)
            const convertBack = DataTransferRate.TeraBytesPerSecond.toMegaBytesPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known MegaBytes Per Second to TeraBytes Per Second', () => {
    expect(DataTransferRate.MegaBytesPerSecond.toTeraBytesPerSecond(80000.0)).toBeCloseTo(0.08, 1);
    expect(DataTransferRate.MegaBytesPerSecond.toTeraBytesPerSecond(12345678.0)).toBeCloseTo(12.345678, 1);
    expect(DataTransferRate.MegaBytesPerSecond.toTeraBytesPerSecond(900800.0)).toBeCloseTo(0.9008, 1);
});

it('From MegaBytes Per Second to Kibibits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.MegaBytesPerSecond.toKibibitsPerSecond(value)
            const convertBack = DataTransferRate.KibibitsPerSecond.toMegaBytesPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known MegaBytes Per Second to Kibibits Per Second', () => {
    expect(DataTransferRate.MegaBytesPerSecond.toKibibitsPerSecond(6.0)).toBeCloseTo(46875.0, 1);
    expect(DataTransferRate.MegaBytesPerSecond.toKibibitsPerSecond(0.9)).toBeCloseTo(7031.25, 1);
    expect(DataTransferRate.MegaBytesPerSecond.toKibibitsPerSecond(0.03)).toBeCloseTo(234.375, 1);
});

it('From MegaBytes Per Second to Mebibits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.MegaBytesPerSecond.toMebibitsPerSecond(value)
            const convertBack = DataTransferRate.MebibitsPerSecond.toMegaBytesPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known MegaBytes Per Second to Mebibits Per Second', () => {
    expect(DataTransferRate.MegaBytesPerSecond.toMebibitsPerSecond(0.03)).toBeCloseTo(0.2288818, 1);
    expect(DataTransferRate.MegaBytesPerSecond.toMebibitsPerSecond(4.5)).toBeCloseTo(34.3323, 1);
    expect(DataTransferRate.MegaBytesPerSecond.toMebibitsPerSecond(80.1)).toBeCloseTo(611.1145, 1);
});

it('From TeraBits Per Second to Bits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.TeraBitsPerSecond.toBitsPerSecond(value)
            const convertBack = DataTransferRate.BitsPerSecond.toTeraBitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known TeraBits Per Second to Bits Per Second', () => {
    expect(DataTransferRate.TeraBitsPerSecond.toBitsPerSecond(0.0007)).toBeCloseTo(700000000.0, 1);
    expect(DataTransferRate.TeraBitsPerSecond.toBitsPerSecond(1.23e-6)).toBeCloseTo(1230000.0, 1);
    expect(DataTransferRate.TeraBitsPerSecond.toBitsPerSecond(0.00098)).toBeCloseTo(980000000.0, 1);
});

it('From TeraBits Per Second to KiloBits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.TeraBitsPerSecond.toKiloBitsPerSecond(value)
            const convertBack = DataTransferRate.KiloBitsPerSecond.toTeraBitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known TeraBits Per Second to KiloBits Per Second', () => {
    expect(DataTransferRate.TeraBitsPerSecond.toKiloBitsPerSecond(0.001)).toBeCloseTo(1000000.0, 1);
    expect(DataTransferRate.TeraBitsPerSecond.toKiloBitsPerSecond(6.1e-6)).toBeCloseTo(6100.0, 1);
    expect(DataTransferRate.TeraBitsPerSecond.toKiloBitsPerSecond(0.00009)).toBeCloseTo(90000.0, 1);
});

it('From TeraBits Per Second to MegaBits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.TeraBitsPerSecond.toMegaBitsPerSecond(value)
            const convertBack = DataTransferRate.MegaBitsPerSecond.toTeraBitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known TeraBits Per Second to MegaBits Per Second', () => {
    expect(DataTransferRate.TeraBitsPerSecond.toMegaBitsPerSecond(0.09)).toBeCloseTo(90000.0, 1);
    expect(DataTransferRate.TeraBitsPerSecond.toMegaBitsPerSecond(3.5e-4)).toBeCloseTo(350.0, 1);
    expect(DataTransferRate.TeraBitsPerSecond.toMegaBitsPerSecond(0.0123)).toBeCloseTo(12300.0, 1);
});

it('From TeraBits Per Second to GigaBits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.TeraBitsPerSecond.toGigaBitsPerSecond(value)
            const convertBack = DataTransferRate.GigaBitsPerSecond.toTeraBitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known TeraBits Per Second to GigaBits Per Second', () => {
    expect(DataTransferRate.TeraBitsPerSecond.toGigaBitsPerSecond(0.9)).toBeCloseTo(900.0, 1);
    expect(DataTransferRate.TeraBitsPerSecond.toGigaBitsPerSecond(1.45)).toBeCloseTo(1450.0, 1);
    expect(DataTransferRate.TeraBitsPerSecond.toGigaBitsPerSecond(8.19)).toBeCloseTo(8190.0, 1);
});

it('From TeraBits Per Second to KiloBytes Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.TeraBitsPerSecond.toKiloBytesPerSecond(value)
            const convertBack = DataTransferRate.KiloBytesPerSecond.toTeraBitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known TeraBits Per Second to KiloBytes Per Second', () => {
    expect(DataTransferRate.TeraBitsPerSecond.toKiloBytesPerSecond(0.0009)).toBeCloseTo(112500.0, 1);
    expect(DataTransferRate.TeraBitsPerSecond.toKiloBytesPerSecond(3.14e-6)).toBeCloseTo(392.5, 1);
    expect(DataTransferRate.TeraBitsPerSecond.toKiloBytesPerSecond(0.001)).toBeCloseTo(125000.0, 1);
});

it('From TeraBits Per Second to MegaBytes Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.TeraBitsPerSecond.toMegaBytesPerSecond(value)
            const convertBack = DataTransferRate.MegaBytesPerSecond.toTeraBitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known TeraBits Per Second to MegaBytes Per Second', () => {
    expect(DataTransferRate.TeraBitsPerSecond.toMegaBytesPerSecond(0.4)).toBeCloseTo(50000.0, 1);
    expect(DataTransferRate.TeraBitsPerSecond.toMegaBytesPerSecond(3.9e-3)).toBeCloseTo(487.5, 1);
    expect(DataTransferRate.TeraBitsPerSecond.toMegaBytesPerSecond(0.007)).toBeCloseTo(875.0, 1);
});

it('From TeraBits Per Second to GigaBytes Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.TeraBitsPerSecond.toGigaBytesPerSecond(value)
            const convertBack = DataTransferRate.GigaBytesPerSecond.toTeraBitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known TeraBits Per Second to GigaBytes Per Second', () => {
    expect(DataTransferRate.TeraBitsPerSecond.toGigaBytesPerSecond(0.009)).toBeCloseTo(1.125, 1);
    expect(DataTransferRate.TeraBitsPerSecond.toGigaBytesPerSecond(0.00123)).toBeCloseTo(0.15375, 1);
    expect(DataTransferRate.TeraBitsPerSecond.toGigaBytesPerSecond(8.1e-3)).toBeCloseTo(1.0125, 1);
});

it('From TeraBits Per Second to TeraBytes Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.TeraBitsPerSecond.toTeraBytesPerSecond(value)
            const convertBack = DataTransferRate.TeraBytesPerSecond.toTeraBitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known TeraBits Per Second to TeraBytes Per Second', () => {
    expect(DataTransferRate.TeraBitsPerSecond.toTeraBytesPerSecond(0.3)).toBeCloseTo(0.0375, 1);
    expect(DataTransferRate.TeraBitsPerSecond.toTeraBytesPerSecond(14.0)).toBeCloseTo(1.75, 1);
    expect(DataTransferRate.TeraBitsPerSecond.toTeraBytesPerSecond(0.8)).toBeCloseTo(0.1, 1);
});

it('From TeraBits Per Second to Kibibits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.TeraBitsPerSecond.toKibibitsPerSecond(value)
            const convertBack = DataTransferRate.KibibitsPerSecond.toTeraBitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known TeraBits Per Second to Kibibits Per Second', () => {
    expect(DataTransferRate.TeraBitsPerSecond.toKibibitsPerSecond(0.0009)).toBeCloseTo(878906.25, 1);
    expect(DataTransferRate.TeraBitsPerSecond.toKibibitsPerSecond(6.1e-6)).toBeCloseTo(5957.031, 1);
    expect(DataTransferRate.TeraBitsPerSecond.toKibibitsPerSecond(12e-9)).toBeCloseTo(11.71875, 1);
});

it('From TeraBits Per Second to Mebibits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.TeraBitsPerSecond.toMebibitsPerSecond(value)
            const convertBack = DataTransferRate.MebibitsPerSecond.toTeraBitsPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known TeraBits Per Second to Mebibits Per Second', () => {
    expect(DataTransferRate.TeraBitsPerSecond.toMebibitsPerSecond(0.9)).toBeCloseTo(858306.59999, 1);
    expect(DataTransferRate.TeraBitsPerSecond.toMebibitsPerSecond(4.6e-3)).toBeCloseTo(4386.9, 1);
    expect(DataTransferRate.TeraBitsPerSecond.toMebibitsPerSecond(0.00123)).toBeCloseTo(1173.0194092, 1);
});

it('From TeraBytes Per Second to Bits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.TeraBytesPerSecond.toBitsPerSecond(value)
            const convertBack = DataTransferRate.BitsPerSecond.toTeraBytesPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known TeraBytes Per Second to Bits Per Second', () => {
    expect(DataTransferRate.TeraBytesPerSecond.toBitsPerSecond(0.00008)).toBeCloseTo(640000000.0, 1);
    expect(DataTransferRate.TeraBytesPerSecond.toBitsPerSecond(1.2e-12)).toBeCloseTo(9.6, 1);
    expect(DataTransferRate.TeraBytesPerSecond.toBitsPerSecond(9.0)).toBeCloseTo(7.2e+13, 1);
});

it('From TeraBytes Per Second to KiloBits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.TeraBytesPerSecond.toKiloBitsPerSecond(value)
            const convertBack = DataTransferRate.KiloBitsPerSecond.toTeraBytesPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known TeraBytes Per Second to KiloBits Per Second', () => {
    expect(DataTransferRate.TeraBytesPerSecond.toKiloBitsPerSecond(0.009)).toBeCloseTo(72000000.0, 1);
    expect(DataTransferRate.TeraBytesPerSecond.toKiloBitsPerSecond(1.4e-6)).toBeCloseTo(11200.0, 1);
    expect(DataTransferRate.TeraBytesPerSecond.toKiloBitsPerSecond(6.1e-5)).toBeCloseTo(488000.0, 1);
});

it('From TeraBytes Per Second to MegaBits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.TeraBytesPerSecond.toMegaBitsPerSecond(value)
            const convertBack = DataTransferRate.MegaBitsPerSecond.toTeraBytesPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known TeraBytes Per Second to MegaBits Per Second', () => {
    expect(DataTransferRate.TeraBytesPerSecond.toMegaBitsPerSecond(0.005)).toBeCloseTo(40000.0, 1);
    expect(DataTransferRate.TeraBytesPerSecond.toMegaBitsPerSecond(0.000123)).toBeCloseTo(984.0, 1);
    expect(DataTransferRate.TeraBytesPerSecond.toMegaBitsPerSecond(0.00006)).toBeCloseTo(480.0, 1);
});

it('From TeraBytes Per Second to GigaBits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.TeraBytesPerSecond.toGigaBitsPerSecond(value)
            const convertBack = DataTransferRate.GigaBitsPerSecond.toTeraBytesPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known TeraBytes Per Second to GigaBits Per Second', () => {
    expect(DataTransferRate.TeraBytesPerSecond.toGigaBitsPerSecond(0.008)).toBeCloseTo(64.0, 1);
    expect(DataTransferRate.TeraBytesPerSecond.toGigaBitsPerSecond(3e-7)).toBeCloseTo(0.0024, 1);
    expect(DataTransferRate.TeraBytesPerSecond.toGigaBitsPerSecond(0.00023)).toBeCloseTo(1.84, 1);
});

it('From TeraBytes Per Second to TeraBits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.TeraBytesPerSecond.toTeraBitsPerSecond(value)
            const convertBack = DataTransferRate.TeraBitsPerSecond.toTeraBytesPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known TeraBytes Per Second to TeraBits Per Second', () => {
    expect(DataTransferRate.TeraBytesPerSecond.toTeraBitsPerSecond(5.0)).toBeCloseTo(40.0, 1);
    expect(DataTransferRate.TeraBytesPerSecond.toTeraBitsPerSecond(1.23)).toBeCloseTo(9.84, 1);
    expect(DataTransferRate.TeraBytesPerSecond.toTeraBitsPerSecond(800.0)).toBeCloseTo(6400.0, 1);
});

it('From TeraBytes Per Second to KiloBytes Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.TeraBytesPerSecond.toKiloBytesPerSecond(value)
            const convertBack = DataTransferRate.KiloBytesPerSecond.toTeraBytesPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known TeraBytes Per Second to KiloBytes Per Second', () => {
    expect(DataTransferRate.TeraBytesPerSecond.toKiloBytesPerSecond(0.0009)).toBeCloseTo(900000.0, 1);
    expect(DataTransferRate.TeraBytesPerSecond.toKiloBytesPerSecond(3.14e-7)).toBeCloseTo(314.0, 1);
    expect(DataTransferRate.TeraBytesPerSecond.toKiloBytesPerSecond(0.00063)).toBeCloseTo(630000.0, 1);
});

it('From TeraBytes Per Second to MegaBytes Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.TeraBytesPerSecond.toMegaBytesPerSecond(value)
            const convertBack = DataTransferRate.MegaBytesPerSecond.toTeraBytesPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known TeraBytes Per Second to MegaBytes Per Second', () => {
    expect(DataTransferRate.TeraBytesPerSecond.toMegaBytesPerSecond(0.009)).toBeCloseTo(9000.0, 1);
    expect(DataTransferRate.TeraBytesPerSecond.toMegaBytesPerSecond(0.234)).toBeCloseTo(234000.0, 1);
    expect(DataTransferRate.TeraBytesPerSecond.toMegaBytesPerSecond(2.0)).toBeCloseTo(2e+6, 1);
});

it('From TeraBytes Per Second to GigaBytes Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.TeraBytesPerSecond.toGigaBytesPerSecond(value)
            const convertBack = DataTransferRate.GigaBytesPerSecond.toTeraBytesPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known TeraBytes Per Second to GigaBytes Per Second', () => {
    expect(DataTransferRate.TeraBytesPerSecond.toGigaBytesPerSecond(2.7)).toBeCloseTo(2700.0, 1);
    expect(DataTransferRate.TeraBytesPerSecond.toGigaBytesPerSecond(0.9)).toBeCloseTo(900.0, 1);
    expect(DataTransferRate.TeraBytesPerSecond.toGigaBytesPerSecond(0.0123)).toBeCloseTo(12.3, 1);
});

it('From TeraBytes Per Second to Kibibits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.TeraBytesPerSecond.toKibibitsPerSecond(value)
            const convertBack = DataTransferRate.KibibitsPerSecond.toTeraBytesPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known TeraBytes Per Second to Kibibits Per Second', () => {
    expect(DataTransferRate.TeraBytesPerSecond.toKibibitsPerSecond(0.0009)).toBeCloseTo(7031250.0, 1);
    expect(DataTransferRate.TeraBytesPerSecond.toKibibitsPerSecond(1.23e-5)).toBeCloseTo(96093.75, 1);
    expect(DataTransferRate.TeraBytesPerSecond.toKibibitsPerSecond(0.0001)).toBeCloseTo(781250.0, 1);
});

it('From TeraBytes Per Second to Mebibits Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = DataTransferRate.TeraBytesPerSecond.toMebibitsPerSecond(value)
            const convertBack = DataTransferRate.MebibitsPerSecond.toTeraBytesPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known TeraBytes Per Second to Mebibits Per Second', () => {
    expect(DataTransferRate.TeraBytesPerSecond.toMebibitsPerSecond(0.01)).toBeCloseTo(76293.95, 1);
    expect(DataTransferRate.TeraBytesPerSecond.toMebibitsPerSecond(0.008)).toBeCloseTo(61035.156, 1);
    expect(DataTransferRate.TeraBytesPerSecond.toMebibitsPerSecond(2.0)).toBeCloseTo(15258789.0625, 1);
});

