// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

import * as fc from 'fast-check';
import { MagnetomotiveForce } from '../src/MagnetomotiveForce';

it('From Ampere-turns to Gilberts and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = MagnetomotiveForce.Ampereturns.toGilberts(value)
            const convertBack = MagnetomotiveForce.Gilberts.toAmpereturns(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Ampere-turns to Gilberts', () => {
    expect(MagnetomotiveForce.Ampereturns.toGilberts(400.0)).toBeCloseTo(502.6548248, 1);
    expect(MagnetomotiveForce.Ampereturns.toGilberts(6.7)).toBeCloseTo(8.4194683154, 1);
    expect(MagnetomotiveForce.Ampereturns.toGilberts(0.8)).toBeCloseTo(1.0053096496, 1);
});

it('From Gilberts to Ampere-turns and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = MagnetomotiveForce.Gilberts.toAmpereturns(value)
            const convertBack = MagnetomotiveForce.Ampereturns.toGilberts(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Gilberts to Ampere-turns', () => {
    expect(MagnetomotiveForce.Gilberts.toAmpereturns(0.8)).toBeCloseTo(0.6366197721, 1);
    expect(MagnetomotiveForce.Gilberts.toAmpereturns(67.0)).toBeCloseTo(53.316905912, 1);
    expect(MagnetomotiveForce.Gilberts.toAmpereturns(2.3)).toBeCloseTo(1.8302818447, 1);
});

