// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

import * as fc from 'fast-check';
import { Mass } from '../src/Mass';

it('From Carats to Milligrams and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Mass.Carats.toMilligrams(value)
            const convertBack = Mass.Milligrams.toCarats(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Carats to Milligrams', () => {
    expect(Mass.Carats.toMilligrams(2.1)).toBeCloseTo(420.0, 1);
    expect(Mass.Carats.toMilligrams(123.0)).toBeCloseTo(24600.0, 1);
    expect(Mass.Carats.toMilligrams(0.8)).toBeCloseTo(160.0, 1);
});

it('From Carats to Grams and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Mass.Carats.toGrams(value)
            const convertBack = Mass.Grams.toCarats(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Carats to Grams', () => {
    expect(Mass.Carats.toGrams(0.8)).toBeCloseTo(0.16, 1);
    expect(Mass.Carats.toGrams(1.5)).toBeCloseTo(0.3, 1);
    expect(Mass.Carats.toGrams(12.0)).toBeCloseTo(2.4, 1);
});

it('From Carats to Kilograms and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Mass.Carats.toKilograms(value)
            const convertBack = Mass.Kilograms.toCarats(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Carats to Kilograms', () => {
    expect(Mass.Carats.toKilograms(1009.0)).toBeCloseTo(0.2018, 1);
    expect(Mass.Carats.toKilograms(999.0)).toBeCloseTo(0.1998, 1);
    expect(Mass.Carats.toKilograms(1234.5)).toBeCloseTo(0.2469, 1);
});

it('From Carats to Tonnes and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Mass.Carats.toTonnes(value)
            const convertBack = Mass.Tonnes.toCarats(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Carats to Tonnes', () => {
    expect(Mass.Carats.toTonnes(1234567.0)).toBeCloseTo(0.2469134, 1);
    expect(Mass.Carats.toTonnes(9999999.0)).toBeCloseTo(1.9999998, 1);
    expect(Mass.Carats.toTonnes(998877.99)).toBeCloseTo(0.199775598, 1);
});

it('From Carats to Ounces and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Mass.Carats.toOunces(value)
            const convertBack = Mass.Ounces.toCarats(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Carats to Ounces', () => {
    expect(Mass.Carats.toOunces(900.0)).toBeCloseTo(6.34931, 1);
    expect(Mass.Carats.toOunces(123.45)).toBeCloseTo(0.870914121, 1);
    expect(Mass.Carats.toOunces(800.0)).toBeCloseTo(5.64383, 1);
});

it('From Carats to Pounds and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Mass.Carats.toPounds(value)
            const convertBack = Mass.Pounds.toCarats(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Carats to Pounds', () => {
    expect(Mass.Carats.toPounds(1000.0)).toBeCloseTo(0.440925, 1);
    expect(Mass.Carats.toPounds(123456.0)).toBeCloseTo(54.4347781, 1);
    expect(Mass.Carats.toPounds(800.0)).toBeCloseTo(0.35274, 1);
});

it('From Carats to Stones and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Mass.Carats.toStones(value)
            const convertBack = Mass.Stones.toCarats(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Carats to Stones', () => {
    expect(Mass.Carats.toStones(9000.0)).toBeCloseTo(0.2834515, 1);
    expect(Mass.Carats.toStones(123456.0)).toBeCloseTo(3.88819843, 1);
    expect(Mass.Carats.toStones(80000.8)).toBeCloseTo(2.519593906, 1);
});

it('From Grams to Milligrams and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Mass.Grams.toMilligrams(value)
            const convertBack = Mass.Milligrams.toGrams(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Grams to Milligrams', () => {
    expect(Mass.Grams.toMilligrams(1.2)).toBeCloseTo(1200.0, 1);
    expect(Mass.Grams.toMilligrams(0.9)).toBeCloseTo(900.0, 1);
    expect(Mass.Grams.toMilligrams(2.0)).toBeCloseTo(2000.0, 1);
});

it('From Grams to Kilograms and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Mass.Grams.toKilograms(value)
            const convertBack = Mass.Kilograms.toGrams(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Grams to Kilograms', () => {
    expect(Mass.Grams.toKilograms(900.0)).toBeCloseTo(0.9, 1);
    expect(Mass.Grams.toKilograms(12345.0)).toBeCloseTo(12.345, 1);
    expect(Mass.Grams.toKilograms(670.0)).toBeCloseTo(0.67, 1);
});

it('From Grams to Tonnes and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Mass.Grams.toTonnes(value)
            const convertBack = Mass.Tonnes.toGrams(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Grams to Tonnes', () => {
    expect(Mass.Grams.toTonnes(6700000.0)).toBeCloseTo(6.7, 1);
    expect(Mass.Grams.toTonnes(123456.0)).toBeCloseTo(0.123456, 1);
    expect(Mass.Grams.toTonnes(9809789.0)).toBeCloseTo(9.809789, 1);
});

it('From Grams to Ounces and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Mass.Grams.toOunces(value)
            const convertBack = Mass.Ounces.toGrams(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Grams to Ounces', () => {
    expect(Mass.Grams.toOunces(4.3)).toBeCloseTo(0.151678, 1);
    expect(Mass.Grams.toOunces(170.0)).toBeCloseTo(5.99657, 1);
    expect(Mass.Grams.toOunces(9.0)).toBeCloseTo(0.317466, 1);
});

it('From Grams to Pounds and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Mass.Grams.toPounds(value)
            const convertBack = Mass.Pounds.toGrams(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Grams to Pounds', () => {
    expect(Mass.Grams.toPounds(80.0)).toBeCloseTo(0.17637, 1);
    expect(Mass.Grams.toPounds(190.0)).toBeCloseTo(0.418878, 1);
    expect(Mass.Grams.toPounds(4500.0)).toBeCloseTo(9.920802, 1);
});

it('From Grams to Stones and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Mass.Grams.toStones(value)
            const convertBack = Mass.Stones.toGrams(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Grams to Stones', () => {
    expect(Mass.Grams.toStones(8000.0)).toBeCloseTo(1.259784, 1);
    expect(Mass.Grams.toStones(12345.0)).toBeCloseTo(1.9440047, 1);
    expect(Mass.Grams.toStones(900.0)).toBeCloseTo(0.141726, 1);
});

it('From Grams to Carats and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Mass.Grams.toCarats(value)
            const convertBack = Mass.Carats.toGrams(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Grams to Carats', () => {
    expect(Mass.Grams.toCarats(123.0)).toBeCloseTo(615.0, 1);
    expect(Mass.Grams.toCarats(90.1)).toBeCloseTo(450.5, 1);
    expect(Mass.Grams.toCarats(5000.0)).toBeCloseTo(25000.0, 1);
});

it('From Kilograms to Milligrams and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Mass.Kilograms.toMilligrams(value)
            const convertBack = Mass.Milligrams.toKilograms(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Kilograms to Milligrams', () => {
    expect(Mass.Kilograms.toMilligrams(0.9)).toBeCloseTo(900000.0, 1);
    expect(Mass.Kilograms.toMilligrams(0.56)).toBeCloseTo(560000.0, 1);
    expect(Mass.Kilograms.toMilligrams(0.007)).toBeCloseTo(7000.0, 1);
});

it('From Kilograms to Grams and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Mass.Kilograms.toGrams(value)
            const convertBack = Mass.Grams.toKilograms(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Kilograms to Grams', () => {
    expect(Mass.Kilograms.toGrams(0.8)).toBeCloseTo(800.0, 1);
    expect(Mass.Kilograms.toGrams(12.0)).toBeCloseTo(12000.0, 1);
    expect(Mass.Kilograms.toGrams(0.2)).toBeCloseTo(200.0, 1);
});

it('From Kilograms to Tonnes and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Mass.Kilograms.toTonnes(value)
            const convertBack = Mass.Tonnes.toKilograms(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Kilograms to Tonnes', () => {
    expect(Mass.Kilograms.toTonnes(123.0)).toBeCloseTo(0.123, 1);
    expect(Mass.Kilograms.toTonnes(9000.0)).toBeCloseTo(9.0, 1);
    expect(Mass.Kilograms.toTonnes(2300.0)).toBeCloseTo(2.3, 1);
});

it('From Kilograms to Ounces and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Mass.Kilograms.toOunces(value)
            const convertBack = Mass.Ounces.toKilograms(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Kilograms to Ounces', () => {
    expect(Mass.Kilograms.toOunces(2300.0)).toBeCloseTo(81130.19, 1);
    expect(Mass.Kilograms.toOunces(12.0)).toBeCloseTo(423.288, 1);
    expect(Mass.Kilograms.toOunces(3.4)).toBeCloseTo(119.931, 1);
});

it('From Kilograms to Pounds and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Mass.Kilograms.toPounds(value)
            const convertBack = Mass.Pounds.toKilograms(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Kilograms to Pounds', () => {
    expect(Mass.Kilograms.toPounds(3.4)).toBeCloseTo(7.49572, 1);
    expect(Mass.Kilograms.toPounds(0.9)).toBeCloseTo(1.98416, 1);
    expect(Mass.Kilograms.toPounds(3.0)).toBeCloseTo(6.61387, 1);
});

it('From Kilograms to Stones and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Mass.Kilograms.toStones(value)
            const convertBack = Mass.Stones.toKilograms(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Kilograms to Stones', () => {
    expect(Mass.Kilograms.toStones(3.0)).toBeCloseTo(0.472419, 1);
    expect(Mass.Kilograms.toStones(98.0)).toBeCloseTo(15.4324, 1);
    expect(Mass.Kilograms.toStones(1.2)).toBeCloseTo(0.188968, 1);
});

it('From Kilograms to Carats and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Mass.Kilograms.toCarats(value)
            const convertBack = Mass.Carats.toKilograms(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Kilograms to Carats', () => {
    expect(Mass.Kilograms.toCarats(0.1)).toBeCloseTo(500.0, 1);
    expect(Mass.Kilograms.toCarats(0.08)).toBeCloseTo(400.0, 1);
    expect(Mass.Kilograms.toCarats(2.0)).toBeCloseTo(10000.0, 1);
});

it('From Milligrams to Grams and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Mass.Milligrams.toGrams(value)
            const convertBack = Mass.Grams.toMilligrams(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Milligrams to Grams', () => {
    expect(Mass.Milligrams.toGrams(190.0)).toBeCloseTo(0.19, 1);
    expect(Mass.Milligrams.toGrams(2300.0)).toBeCloseTo(2.3, 1);
    expect(Mass.Milligrams.toGrams(19000.0)).toBeCloseTo(19.0, 1);
});

it('From Milligrams to Kilograms and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Mass.Milligrams.toKilograms(value)
            const convertBack = Mass.Kilograms.toMilligrams(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Milligrams to Kilograms', () => {
    expect(Mass.Milligrams.toKilograms(1234567.0)).toBeCloseTo(1.234567, 1);
    expect(Mass.Milligrams.toKilograms(900800.0)).toBeCloseTo(0.9008, 1);
    expect(Mass.Milligrams.toKilograms(7800000.0)).toBeCloseTo(7.8, 1);
});

it('From Milligrams to Tonnes and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Mass.Milligrams.toTonnes(value)
            const convertBack = Mass.Tonnes.toMilligrams(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Milligrams to Tonnes', () => {
    expect(Mass.Milligrams.toTonnes(900000000.0)).toBeCloseTo(0.9, 1);
    expect(Mass.Milligrams.toTonnes(60000000.0)).toBeCloseTo(0.06, 1);
    expect(Mass.Milligrams.toTonnes(123456789.0)).toBeCloseTo(0.123456789, 1);
});

it('From Milligrams to Ounces and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Mass.Milligrams.toOunces(value)
            const convertBack = Mass.Ounces.toMilligrams(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Milligrams to Ounces', () => {
    expect(Mass.Milligrams.toOunces(6000.0)).toBeCloseTo(0.2116438, 1);
    expect(Mass.Milligrams.toOunces(123456.0)).toBeCloseTo(4.35478225, 1);
    expect(Mass.Milligrams.toOunces(8001.0)).toBeCloseTo(0.282227, 1);
});

it('From Milligrams to Pounds and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Mass.Milligrams.toPounds(value)
            const convertBack = Mass.Pounds.toMilligrams(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Milligrams to Pounds', () => {
    expect(Mass.Milligrams.toPounds(123456.0)).toBeCloseTo(0.27217389, 1);
    expect(Mass.Milligrams.toPounds(800900.0)).toBeCloseTo(1.76568226, 1);
    expect(Mass.Milligrams.toPounds(666666.0)).toBeCloseTo(1.46974694, 1);
});

it('From Milligrams to Stones and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Mass.Milligrams.toStones(value)
            const convertBack = Mass.Stones.toMilligrams(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Milligrams to Stones', () => {
    expect(Mass.Milligrams.toStones(900000.0)).toBeCloseTo(0.14172574, 1);
    expect(Mass.Milligrams.toStones(12345678.0)).toBeCloseTo(1.9441115001, 1);
    expect(Mass.Milligrams.toStones(800100.0)).toBeCloseTo(0.125994183, 1);
});

it('From Milligrams to Carats and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Mass.Milligrams.toCarats(value)
            const convertBack = Mass.Carats.toMilligrams(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Milligrams to Carats', () => {
    expect(Mass.Milligrams.toCarats(600.0)).toBeCloseTo(3.0, 1);
    expect(Mass.Milligrams.toCarats(1234.0)).toBeCloseTo(6.17, 1);
    expect(Mass.Milligrams.toCarats(9090.0)).toBeCloseTo(45.45, 1);
});

it('From Ounces to Milligrams and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Mass.Ounces.toMilligrams(value)
            const convertBack = Mass.Milligrams.toOunces(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Ounces to Milligrams', () => {
    expect(Mass.Ounces.toMilligrams(0.2)).toBeCloseTo(5669.9, 1);
    expect(Mass.Ounces.toMilligrams(12.0)).toBeCloseTo(340194.2772, 1);
    expect(Mass.Ounces.toMilligrams(1.8)).toBeCloseTo(51029.141579, 1);
});

it('From Ounces to Grams and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Mass.Ounces.toGrams(value)
            const convertBack = Mass.Grams.toOunces(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Ounces to Grams', () => {
    expect(Mass.Ounces.toGrams(2.0)).toBeCloseTo(56.699, 1);
    expect(Mass.Ounces.toGrams(0.3)).toBeCloseTo(8.50486, 1);
    expect(Mass.Ounces.toGrams(7.0)).toBeCloseTo(198.447, 1);
});

it('From Ounces to Kilograms and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Mass.Ounces.toKilograms(value)
            const convertBack = Mass.Kilograms.toOunces(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Ounces to Kilograms', () => {
    expect(Mass.Ounces.toKilograms(56.0)).toBeCloseTo(1.58757, 1);
    expect(Mass.Ounces.toKilograms(123.0)).toBeCloseTo(3.48699, 1);
    expect(Mass.Ounces.toKilograms(100.9)).toBeCloseTo(2.8604669, 1);
});

it('From Ounces to Tonnes and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Mass.Ounces.toTonnes(value)
            const convertBack = Mass.Tonnes.toOunces(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Ounces to Tonnes', () => {
    expect(Mass.Ounces.toTonnes(8000.0)).toBeCloseTo(0.2267962, 1);
    expect(Mass.Ounces.toTonnes(1234567.0)).toBeCloseTo(34.99938572, 1);
    expect(Mass.Ounces.toTonnes(900800.0)).toBeCloseTo(25.5372504, 1);
});

it('From Ounces to Pounds and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Mass.Ounces.toPounds(value)
            const convertBack = Mass.Pounds.toOunces(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Ounces to Pounds', () => {
    expect(Mass.Ounces.toPounds(90.0)).toBeCloseTo(5.625, 1);
    expect(Mass.Ounces.toPounds(5.2)).toBeCloseTo(0.325, 1);
    expect(Mass.Ounces.toPounds(12.0)).toBeCloseTo(0.75, 1);
});

it('From Ounces to Stones and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Mass.Ounces.toStones(value)
            const convertBack = Mass.Stones.toOunces(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Ounces to Stones', () => {
    expect(Mass.Ounces.toStones(167.0)).toBeCloseTo(0.745536, 1);
    expect(Mass.Ounces.toStones(800.7)).toBeCloseTo(3.5745536, 1);
    expect(Mass.Ounces.toStones(1234.5)).toBeCloseTo(5.51116071, 1);
});

it('From Ounces to Carats and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Mass.Ounces.toCarats(value)
            const convertBack = Mass.Carats.toOunces(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Ounces to Carats', () => {
    expect(Mass.Ounces.toCarats(0.0012)).toBeCloseTo(0.170097139, 1);
    expect(Mass.Ounces.toCarats(4.0)).toBeCloseTo(566.99, 1);
    expect(Mass.Ounces.toCarats(1.4)).toBeCloseTo(198.447, 1);
});

it('From Pounds to Milligrams and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Mass.Pounds.toMilligrams(value)
            const convertBack = Mass.Milligrams.toPounds(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Pounds to Milligrams', () => {
    expect(Mass.Pounds.toMilligrams(2.2)).toBeCloseTo(997903.214, 1);
    expect(Mass.Pounds.toMilligrams(0.7)).toBeCloseTo(317514.6589, 1);
    expect(Mass.Pounds.toMilligrams(0.32)).toBeCloseTo(145149.5584, 1);
});

it('From Pounds to Grams and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Mass.Pounds.toGrams(value)
            const convertBack = Mass.Grams.toPounds(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Pounds to Grams', () => {
    expect(Mass.Pounds.toGrams(0.3)).toBeCloseTo(136.078, 1);
    expect(Mass.Pounds.toGrams(1.2)).toBeCloseTo(544.311, 1);
    expect(Mass.Pounds.toGrams(9.0)).toBeCloseTo(4082.33, 1);
});

it('From Pounds to Kilograms and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Mass.Pounds.toKilograms(value)
            const convertBack = Mass.Kilograms.toPounds(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Pounds to Kilograms', () => {
    expect(Mass.Pounds.toKilograms(5.0)).toBeCloseTo(2.26796, 1);
    expect(Mass.Pounds.toKilograms(1.1)).toBeCloseTo(0.498952, 1);
    expect(Mass.Pounds.toKilograms(0.7)).toBeCloseTo(0.317515, 1);
});

it('From Pounds to Tonnes and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Mass.Pounds.toTonnes(value)
            const convertBack = Mass.Tonnes.toPounds(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Pounds to Tonnes', () => {
    expect(Mass.Pounds.toTonnes(1233.0)).toBeCloseTo(0.5592794, 1);
    expect(Mass.Pounds.toTonnes(656565.0)).toBeCloseTo(297.812874, 1);
    expect(Mass.Pounds.toTonnes(900.0)).toBeCloseTo(0.408233, 1);
});

it('From Pounds to Ounces and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Mass.Pounds.toOunces(value)
            const convertBack = Mass.Ounces.toPounds(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Pounds to Ounces', () => {
    expect(Mass.Pounds.toOunces(45.0)).toBeCloseTo(720.0, 1);
    expect(Mass.Pounds.toOunces(6.7)).toBeCloseTo(107.2, 1);
    expect(Mass.Pounds.toOunces(89.1)).toBeCloseTo(1425.6, 1);
});

it('From Pounds to Stones and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Mass.Pounds.toStones(value)
            const convertBack = Mass.Stones.toPounds(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Pounds to Stones', () => {
    expect(Mass.Pounds.toStones(89.1)).toBeCloseTo(6.364286, 1);
    expect(Mass.Pounds.toStones(1.2)).toBeCloseTo(0.0857143, 1);
    expect(Mass.Pounds.toStones(789.0)).toBeCloseTo(56.3571, 1);
});

it('From Pounds to Carats and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Mass.Pounds.toCarats(value)
            const convertBack = Mass.Carats.toPounds(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Pounds to Carats', () => {
    expect(Mass.Pounds.toCarats(80.0)).toBeCloseTo(181436.7522, 1);
    expect(Mass.Pounds.toCarats(2.34)).toBeCloseTo(5307.031, 1);
    expect(Mass.Pounds.toCarats(0.9)).toBeCloseTo(2041.17, 1);
});

it('From Stones to Milligrams and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Mass.Stones.toMilligrams(value)
            const convertBack = Mass.Milligrams.toStones(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Stones to Milligrams', () => {
    expect(Mass.Stones.toMilligrams(0.009)).toBeCloseTo(57152.63861, 1);
    expect(Mass.Stones.toMilligrams(0.002)).toBeCloseTo(12700.586, 1);
    expect(Mass.Stones.toMilligrams(0.0006)).toBeCloseTo(3810.17591, 1);
});

it('From Stones to Grams and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Mass.Stones.toGrams(value)
            const convertBack = Mass.Grams.toStones(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Stones to Grams', () => {
    expect(Mass.Stones.toGrams(1.2)).toBeCloseTo(7620.35, 1);
    expect(Mass.Stones.toGrams(8.0)).toBeCloseTo(50802.34543, 1);
    expect(Mass.Stones.toGrams(90.0)).toBeCloseTo(571526.38619, 1);
});

it('From Stones to Kilograms and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Mass.Stones.toKilograms(value)
            const convertBack = Mass.Kilograms.toStones(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Stones to Kilograms', () => {
    expect(Mass.Stones.toKilograms(90.0)).toBeCloseTo(571.526, 1);
    expect(Mass.Stones.toKilograms(3.4)).toBeCloseTo(21.591, 1);
    expect(Mass.Stones.toKilograms(66.0)).toBeCloseTo(419.119, 1);
});

it('From Stones to Tonnes and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Mass.Stones.toTonnes(value)
            const convertBack = Mass.Tonnes.toStones(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Stones to Tonnes', () => {
    expect(Mass.Stones.toTonnes(100.0)).toBeCloseTo(0.635029, 1);
    expect(Mass.Stones.toTonnes(12345.0)).toBeCloseTo(78.394369, 1);
    expect(Mass.Stones.toTonnes(10099.0)).toBeCloseTo(64.131611, 1);
});

it('From Stones to Ounces and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Mass.Stones.toOunces(value)
            const convertBack = Mass.Ounces.toStones(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Stones to Ounces', () => {
    expect(Mass.Stones.toOunces(34.0)).toBeCloseTo(7616.0, 1);
    expect(Mass.Stones.toOunces(1.2)).toBeCloseTo(268.8, 1);
    expect(Mass.Stones.toOunces(800.0)).toBeCloseTo(179200.0, 1);
});

it('From Stones to Pounds and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Mass.Stones.toPounds(value)
            const convertBack = Mass.Pounds.toStones(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Stones to Pounds', () => {
    expect(Mass.Stones.toPounds(800.0)).toBeCloseTo(11200.0, 1);
    expect(Mass.Stones.toPounds(0.5)).toBeCloseTo(7.0, 1);
    expect(Mass.Stones.toPounds(52.1)).toBeCloseTo(729.4, 1);
});

it('From Stones to Carats and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Mass.Stones.toCarats(value)
            const convertBack = Mass.Carats.toStones(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Stones to Carats', () => {
    expect(Mass.Stones.toCarats(0.01)).toBeCloseTo(317.5147, 1);
    expect(Mass.Stones.toCarats(0.006)).toBeCloseTo(190.5088, 1);
    expect(Mass.Stones.toCarats(2.1)).toBeCloseTo(66677.25, 1);
});

it('From Tonnes to Milligrams and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Mass.Tonnes.toMilligrams(value)
            const convertBack = Mass.Milligrams.toTonnes(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Tonnes to Milligrams', () => {
    expect(Mass.Tonnes.toMilligrams(0.009)).toBeCloseTo(9000000.0, 1);
    expect(Mass.Tonnes.toMilligrams(0.00081)).toBeCloseTo(810000.0, 1);
    expect(Mass.Tonnes.toMilligrams(0.00123)).toBeCloseTo(1230000.0, 1);
});

it('From Tonnes to Grams and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Mass.Tonnes.toGrams(value)
            const convertBack = Mass.Grams.toTonnes(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Tonnes to Grams', () => {
    expect(Mass.Tonnes.toGrams(0.00123)).toBeCloseTo(1230.0, 1);
    expect(Mass.Tonnes.toGrams(0.8)).toBeCloseTo(800000.0, 1);
    expect(Mass.Tonnes.toGrams(0.03)).toBeCloseTo(30000.0, 1);
});

it('From Tonnes to Kilograms and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Mass.Tonnes.toKilograms(value)
            const convertBack = Mass.Kilograms.toTonnes(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Tonnes to Kilograms', () => {
    expect(Mass.Tonnes.toKilograms(0.03)).toBeCloseTo(30.0, 1);
    expect(Mass.Tonnes.toKilograms(4.0)).toBeCloseTo(4000.0, 1);
    expect(Mass.Tonnes.toKilograms(1.2)).toBeCloseTo(1200.0, 1);
});

it('From Tonnes to Ounces and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Mass.Tonnes.toOunces(value)
            const convertBack = Mass.Ounces.toTonnes(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Tonnes to Ounces', () => {
    expect(Mass.Tonnes.toOunces(1.2)).toBeCloseTo(42328.754376824065, 1);
    expect(Mass.Tonnes.toOunces(0.8)).toBeCloseTo(28219.169584549378, 1);
    expect(Mass.Tonnes.toOunces(0.001)).toBeCloseTo(35.273962, 1);
});

it('From Tonnes to Pounds and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Mass.Tonnes.toPounds(value)
            const convertBack = Mass.Pounds.toTonnes(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Tonnes to Pounds', () => {
    expect(Mass.Tonnes.toPounds(1.2)).toBeCloseTo(2645.55, 1);
    expect(Mass.Tonnes.toPounds(0.9)).toBeCloseTo(1984.16, 1);
    expect(Mass.Tonnes.toPounds(34.0)).toBeCloseTo(74957.08, 1);
});

it('From Tonnes to Stones and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Mass.Tonnes.toStones(value)
            const convertBack = Mass.Stones.toTonnes(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Tonnes to Stones', () => {
    expect(Mass.Tonnes.toStones(12.0)).toBeCloseTo(1889.68, 1);
    expect(Mass.Tonnes.toStones(8.4)).toBeCloseTo(1322.77, 1);
    expect(Mass.Tonnes.toStones(0.3)).toBeCloseTo(47.2419, 1);
});

it('From Tonnes to Carats and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Mass.Tonnes.toCarats(value)
            const convertBack = Mass.Carats.toTonnes(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Tonnes to Carats', () => {
    expect(Mass.Tonnes.toCarats(0.003)).toBeCloseTo(15000.0, 1);
    expect(Mass.Tonnes.toCarats(0.09)).toBeCloseTo(450000.0, 1);
    expect(Mass.Tonnes.toCarats(0.0012)).toBeCloseTo(6000.0, 1);
});

