// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

import * as fc from 'fast-check';
import { Speed } from '../src/Speed';

it('From Feet Per Second to Miles Per Hour and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Speed.FeetPerSecond.toMilesPerHour(value)
            const convertBack = Speed.MilesPerHour.toFeetPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Feet Per Second to Miles Per Hour', () => {
    expect(Speed.FeetPerSecond.toMilesPerHour(14.5)).toBeCloseTo(9.886364, 1);
    expect(Speed.FeetPerSecond.toMilesPerHour(100.0)).toBeCloseTo(68.1818, 1);
    expect(Speed.FeetPerSecond.toMilesPerHour(1.6)).toBeCloseTo(1.09091, 1);
});

it('From Feet Per Second to Kilometres Per Hour and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Speed.FeetPerSecond.toKilometresPerHour(value)
            const convertBack = Speed.KilometresPerHour.toFeetPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Feet Per Second to Kilometres Per Hour', () => {
    expect(Speed.FeetPerSecond.toKilometresPerHour(1.5)).toBeCloseTo(1.64592, 1);
    expect(Speed.FeetPerSecond.toKilometresPerHour(67.9)).toBeCloseTo(74.50531, 1);
    expect(Speed.FeetPerSecond.toKilometresPerHour(109.0)).toBeCloseTo(119.604, 1);
});

it('From Feet Per Second to Metres Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Speed.FeetPerSecond.toMetresPerSecond(value)
            const convertBack = Speed.MetresPerSecond.toFeetPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Feet Per Second to Metres Per Second', () => {
    expect(Speed.FeetPerSecond.toMetresPerSecond(10.8)).toBeCloseTo(3.29184, 1);
    expect(Speed.FeetPerSecond.toMetresPerSecond(66.0)).toBeCloseTo(20.1168, 1);
    expect(Speed.FeetPerSecond.toMetresPerSecond(2.3)).toBeCloseTo(0.70104, 1);
});

it('From Feet Per Second to Knots and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Speed.FeetPerSecond.toKnots(value)
            const convertBack = Speed.Knots.toFeetPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Feet Per Second to Knots', () => {
    expect(Speed.FeetPerSecond.toKnots(2.3)).toBeCloseTo(1.36271, 1);
    expect(Speed.FeetPerSecond.toKnots(666.0)).toBeCloseTo(394.594, 1);
    expect(Speed.FeetPerSecond.toKnots(17.1)).toBeCloseTo(10.13147, 1);
});

it('From Kilometres Per Hour to Miles Per Hour and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Speed.KilometresPerHour.toMilesPerHour(value)
            const convertBack = Speed.MilesPerHour.toKilometresPerHour(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Kilometres Per Hour to Miles Per Hour', () => {
    expect(Speed.KilometresPerHour.toMilesPerHour(67.0)).toBeCloseTo(41.6319, 1);
    expect(Speed.KilometresPerHour.toMilesPerHour(12.0)).toBeCloseTo(7.45645, 1);
    expect(Speed.KilometresPerHour.toMilesPerHour(6.3)).toBeCloseTo(3.91464, 1);
});

it('From Kilometres Per Hour to Feet Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Speed.KilometresPerHour.toFeetPerSecond(value)
            const convertBack = Speed.FeetPerSecond.toKilometresPerHour(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Kilometres Per Hour to Feet Per Second', () => {
    expect(Speed.KilometresPerHour.toFeetPerSecond(5.0)).toBeCloseTo(4.55672, 1);
    expect(Speed.KilometresPerHour.toFeetPerSecond(1.5)).toBeCloseTo(1.36702, 1);
    expect(Speed.KilometresPerHour.toFeetPerSecond(89.8)).toBeCloseTo(81.83873, 1);
});

it('From Kilometres Per Hour to Metres Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Speed.KilometresPerHour.toMetresPerSecond(value)
            const convertBack = Speed.MetresPerSecond.toKilometresPerHour(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Kilometres Per Hour to Metres Per Second', () => {
    expect(Speed.KilometresPerHour.toMetresPerSecond(67.0)).toBeCloseTo(18.6111, 1);
    expect(Speed.KilometresPerHour.toMetresPerSecond(5.9)).toBeCloseTo(1.63889, 1);
    expect(Speed.KilometresPerHour.toMetresPerSecond(900.0)).toBeCloseTo(250.0, 1);
});

it('From Kilometres Per Hour to Knots and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Speed.KilometresPerHour.toKnots(value)
            const convertBack = Speed.Knots.toKilometresPerHour(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Kilometres Per Hour to Knots', () => {
    expect(Speed.KilometresPerHour.toKnots(900.0)).toBeCloseTo(485.961, 1);
    expect(Speed.KilometresPerHour.toKnots(3.9)).toBeCloseTo(2.10583, 1);
    expect(Speed.KilometresPerHour.toKnots(12.0)).toBeCloseTo(6.47948, 1);
});

it('From Knots to Miles Per Hour and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Speed.Knots.toMilesPerHour(value)
            const convertBack = Speed.MilesPerHour.toKnots(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Knots to Miles Per Hour', () => {
    expect(Speed.Knots.toMilesPerHour(8.0)).toBeCloseTo(9.20624, 1);
    expect(Speed.Knots.toMilesPerHour(1.2)).toBeCloseTo(1.38094, 1);
    expect(Speed.Knots.toMilesPerHour(670.0)).toBeCloseTo(771.022, 1);
});

it('From Knots to Kilometres Per Hour and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Speed.Knots.toKilometresPerHour(value)
            const convertBack = Speed.KilometresPerHour.toKnots(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Knots to Kilometres Per Hour', () => {
    expect(Speed.Knots.toKilometresPerHour(678.0)).toBeCloseTo(1255.66, 1);
    expect(Speed.Knots.toKilometresPerHour(1.8)).toBeCloseTo(3.3336, 1);
    expect(Speed.Knots.toKilometresPerHour(56.0)).toBeCloseTo(103.712, 1);
});

it('From Knots to Feet Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Speed.Knots.toFeetPerSecond(value)
            const convertBack = Speed.FeetPerSecond.toKnots(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Knots to Feet Per Second', () => {
    expect(Speed.Knots.toFeetPerSecond(56.0)).toBeCloseTo(94.5174, 1);
    expect(Speed.Knots.toFeetPerSecond(4.7)).toBeCloseTo(7.93271, 1);
    expect(Speed.Knots.toFeetPerSecond(3.0)).toBeCloseTo(5.06343, 1);
});

it('From Knots to Metres Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Speed.Knots.toMetresPerSecond(value)
            const convertBack = Speed.MetresPerSecond.toKnots(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Knots to Metres Per Second', () => {
    expect(Speed.Knots.toMetresPerSecond(5.0)).toBeCloseTo(2.57222, 1);
    expect(Speed.Knots.toMetresPerSecond(9.1)).toBeCloseTo(4.68144, 1);
    expect(Speed.Knots.toMetresPerSecond(190.0)).toBeCloseTo(97.7444, 1);
});

it('From Metres Per Second to Miles Per Hour and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Speed.MetresPerSecond.toMilesPerHour(value)
            const convertBack = Speed.MilesPerHour.toMetresPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Metres Per Second to Miles Per Hour', () => {
    expect(Speed.MetresPerSecond.toMilesPerHour(13.0)).toBeCloseTo(29.0802, 1);
    expect(Speed.MetresPerSecond.toMilesPerHour(6.7)).toBeCloseTo(14.9875, 1);
    expect(Speed.MetresPerSecond.toMilesPerHour(140.0)).toBeCloseTo(313.171, 1);
});

it('From Metres Per Second to Kilometres Per Hour and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Speed.MetresPerSecond.toKilometresPerHour(value)
            const convertBack = Speed.KilometresPerHour.toMetresPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Metres Per Second to Kilometres Per Hour', () => {
    expect(Speed.MetresPerSecond.toKilometresPerHour(800.0)).toBeCloseTo(2880.0, 1);
    expect(Speed.MetresPerSecond.toKilometresPerHour(7.8)).toBeCloseTo(28.08, 1);
    expect(Speed.MetresPerSecond.toKilometresPerHour(9000.0)).toBeCloseTo(32400.0, 1);
});

it('From Metres Per Second to Feet Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Speed.MetresPerSecond.toFeetPerSecond(value)
            const convertBack = Speed.FeetPerSecond.toMetresPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Metres Per Second to Feet Per Second', () => {
    expect(Speed.MetresPerSecond.toFeetPerSecond(9000.0)).toBeCloseTo(29527.56, 1);
    expect(Speed.MetresPerSecond.toFeetPerSecond(3.4)).toBeCloseTo(11.1549, 1);
    expect(Speed.MetresPerSecond.toFeetPerSecond(12.0)).toBeCloseTo(39.3701, 1);
});

it('From Metres Per Second to Knots and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Speed.MetresPerSecond.toKnots(value)
            const convertBack = Speed.Knots.toMetresPerSecond(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Metres Per Second to Knots', () => {
    expect(Speed.MetresPerSecond.toKnots(12.0)).toBeCloseTo(23.3261, 1);
    expect(Speed.MetresPerSecond.toKnots(6.3)).toBeCloseTo(12.2462, 1);
    expect(Speed.MetresPerSecond.toKnots(9.0)).toBeCloseTo(17.4946, 1);
});

it('From Miles Per Hour to Kilometres Per Hour and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Speed.MilesPerHour.toKilometresPerHour(value)
            const convertBack = Speed.KilometresPerHour.toMilesPerHour(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Miles Per Hour to Kilometres Per Hour', () => {
    expect(Speed.MilesPerHour.toKilometresPerHour(345.0)).toBeCloseTo(555.224, 1);
    expect(Speed.MilesPerHour.toKilometresPerHour(1.6)).toBeCloseTo(2.57495, 1);
    expect(Speed.MilesPerHour.toKilometresPerHour(0.5)).toBeCloseTo(0.804672, 1);
});

it('From Miles Per Hour to Feet Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Speed.MilesPerHour.toFeetPerSecond(value)
            const convertBack = Speed.FeetPerSecond.toMilesPerHour(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Miles Per Hour to Feet Per Second', () => {
    expect(Speed.MilesPerHour.toFeetPerSecond(0.5)).toBeCloseTo(0.733333, 1);
    expect(Speed.MilesPerHour.toFeetPerSecond(123.0)).toBeCloseTo(180.4, 1);
    expect(Speed.MilesPerHour.toFeetPerSecond(4.5)).toBeCloseTo(6.6, 1);
});

it('From Miles Per Hour to Metres Per Second and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Speed.MilesPerHour.toMetresPerSecond(value)
            const convertBack = Speed.MetresPerSecond.toMilesPerHour(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Miles Per Hour to Metres Per Second', () => {
    expect(Speed.MilesPerHour.toMetresPerSecond(4.5)).toBeCloseTo(2.01168, 1);
    expect(Speed.MilesPerHour.toMetresPerSecond(100.0)).toBeCloseTo(44.704, 1);
    expect(Speed.MilesPerHour.toMetresPerSecond(40.0)).toBeCloseTo(17.8816, 1);
});

it('From Miles Per Hour to Knots and back', () => {
    fc.assert(
        fc.property(fc.float(), value => {
            const convertTo = Speed.MilesPerHour.toKnots(value)
            const convertBack = Speed.Knots.toMilesPerHour(convertTo)

            expect(convertBack).toBeCloseTo(convertBack, 1);
        })
    )
});

it('Convert known Miles Per Hour to Knots', () => {
    expect(Speed.MilesPerHour.toKnots(30.0)).toBeCloseTo(26.0693, 1);
    expect(Speed.MilesPerHour.toKnots(4.5)).toBeCloseTo(3.91039, 1);
    expect(Speed.MilesPerHour.toKnots(55.0)).toBeCloseTo(47.7937, 1);
});

