// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

export namespace Area {
	export class Acres {
		static toSquareKilometres(value: number): number {
			return value / 247.105;
		}
		static toSquareMetres(value: number): number {
			return value * 4046.86;
		}
		static toSquareMiles(value: number): number {
			return value / 640.0;
		}
		static toSquareYards(value: number): number {
			return value * 4840.0;
		}
		static toSquareFeet(value: number): number {
			return value * 43560.0;
		}
		static toSquareInches(value: number): number {
			return value * 6272640.0;
		}
		static toHectares(value: number): number {
			return value / 2.4710538146717;
		}
	}

	export class Hectares {
		static toSquareKilometres(value: number): number {
			return value / 100.0;
		}
		static toSquareMetres(value: number): number {
			return value * 10000.0;
		}
		static toSquareMiles(value: number): number {
			return value / 258.99881103;
		}
		static toSquareYards(value: number): number {
			return value * 11959.900463011;
		}
		static toSquareFeet(value: number): number {
			return value * 107639.0;
		}
		static toSquareInches(value: number): number {
			return value * 15500031.0;
		}
		static toAcres(value: number): number {
			return value * 2.4710538146717;
		}
	}

	export class SquareFeet {
		static toSquareKilometres(value: number): number {
			return value / 10763910.41671;
		}
		static toSquareMetres(value: number): number {
			return value / 10.76391042;
		}
		static toSquareMiles(value: number): number {
			return value / 27878400.0;
		}
		static toSquareYards(value: number): number {
			return value / 9.0;
		}
		static toSquareInches(value: number): number {
			return value * 144.0;
		}
		static toHectares(value: number): number {
			return value / 107639.0;
		}
		static toAcres(value: number): number {
			return value / 43560.0;
		}
	}

	export class SquareInches {
		static toSquareKilometres(value: number): number {
			return value / 1550003100.00;
		}
		static toSquareMetres(value: number): number {
			return value / 1550.0;
		}
		static toSquareMiles(value: number): number {
			return value / 4014489600.0;
		}
		static toSquareYards(value: number): number {
			return value / 1296.0;
		}
		static toSquareFeet(value: number): number {
			return value / 144.0;
		}
		static toHectares(value: number): number {
			return value / 15500031.0;
		}
		static toAcres(value: number): number {
			return value / 6272640.0;
		}
	}

	export class SquareKilometres {
		static toSquareMetres(value: number): number {
			return value * 1e+6;
		}
		static toSquareMiles(value: number): number {
			return value / 2.58999;
		}
		static toSquareYards(value: number): number {
			return value * 1195990.05;
		}
		static toSquareFeet(value: number): number {
			return value * 10763910.41671;
		}
		static toSquareInches(value: number): number {
			return value * 1550003100.00;
		}
		static toHectares(value: number): number {
			return value * 100.0;
		}
		static toAcres(value: number): number {
			return value * 247.105;
		}
	}

	export class SquareMetres {
		static toSquareKilometres(value: number): number {
			return value / 1e+6;
		}
		static toSquareMiles(value: number): number {
			return value / 2589988.10;
		}
		static toSquareYards(value: number): number {
			return value * 1.1959900463;
		}
		static toSquareFeet(value: number): number {
			return value * 10.76391042;
		}
		static toSquareInches(value: number): number {
			return value * 1550.0;
		}
		static toHectares(value: number): number {
			return value / 10000.0;
		}
		static toAcres(value: number): number {
			return value / 4046.86;
		}
	}

	export class SquareMiles {
		static toSquareKilometres(value: number): number {
			return value * 2.58999;
		}
		static toSquareMetres(value: number): number {
			return value * 2589988.10;
		}
		static toSquareYards(value: number): number {
			return value * 3097600.0;
		}
		static toSquareFeet(value: number): number {
			return value * 27878400.0;
		}
		static toSquareInches(value: number): number {
			return value * 4014489600.0;
		}
		static toHectares(value: number): number {
			return value * 258.99881103;
		}
		static toAcres(value: number): number {
			return value * 640.0;
		}
	}

	export class SquareYards {
		static toSquareKilometres(value: number): number {
			return value / 1195990.05;
		}
		static toSquareMetres(value: number): number {
			return value / 1.1959900463;
		}
		static toSquareMiles(value: number): number {
			return value / 3097600.0;
		}
		static toSquareFeet(value: number): number {
			return value * 9.0;
		}
		static toSquareInches(value: number): number {
			return value * 1296.0;
		}
		static toHectares(value: number): number {
			return value / 11959.900463011;
		}
		static toAcres(value: number): number {
			return value / 4840.0;
		}
	}
}
