// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

export namespace DataStorage {
	export class Bits {
		static toKilobits(value: number): number {
			return value / 1000.0;
		}
		static toMegabits(value: number): number {
			return value / 1e+6;
		}
		static toGigabits(value: number): number {
			return value / 1e+9;
		}
		static toTerabits(value: number): number {
			return value / 1e+12;
		}
		static toKilobytes(value: number): number {
			return value / 8000.0;
		}
		static toMegabytes(value: number): number {
			return value / 8e+6;
		}
		static toGigabytes(value: number): number {
			return value / 8e+9;
		}
		static toTerabytes(value: number): number {
			return value / 8e+12;
		}
		static toKibibits(value: number): number {
			return value / 1024.0;
		}
		static toMebibits(value: number): number {
			return value / 1048576.0;
		}
	}

	export class Gigabits {
		static toBits(value: number): number {
			return value * 1e+9;
		}
		static toKilobits(value: number): number {
			return value * 1e+6;
		}
		static toMegabits(value: number): number {
			return value * 1000.0;
		}
		static toTerabits(value: number): number {
			return value / 1000.0;
		}
		static toKilobytes(value: number): number {
			return value * 125000.0;
		}
		static toMegabytes(value: number): number {
			return value * 125.0;
		}
		static toGigabytes(value: number): number {
			return value / 8.0;
		}
		static toTerabytes(value: number): number {
			return value / 8000.0;
		}
		static toKibibits(value: number): number {
			return value * 976562.5;
		}
		static toMebibits(value: number): number {
			return value * 954.0;
		}
	}

	export class Gigabytes {
		static toBits(value: number): number {
			return value * 8e+9;
		}
		static toKilobits(value: number): number {
			return value * 8e+6;
		}
		static toMegabits(value: number): number {
			return value * 8000.0;
		}
		static toGigabits(value: number): number {
			return value * 8.0;
		}
		static toTerabits(value: number): number {
			return value / 125.0;
		}
		static toKilobytes(value: number): number {
			return value * 1e+6;
		}
		static toMegabytes(value: number): number {
			return value * 1000.0;
		}
		static toTerabytes(value: number): number {
			return value / 1000.0;
		}
		static toKibibits(value: number): number {
			return value * 7812500.0;
		}
		static toMebibits(value: number): number {
			return value * 7629.39;
		}
	}

	export class Kibibits {
		static toBits(value: number): number {
			return value * 1024.0;
		}
		static toKilobits(value: number): number {
			return value * 1.024;
		}
		static toMegabits(value: number): number {
			return value / 976.563;
		}
		static toGigabits(value: number): number {
			return value / 976562.5;
		}
		static toTerabits(value: number): number {
			return value / 976562500.0;
		}
		static toKilobytes(value: number): number {
			return value / 7.812;
		}
		static toMegabytes(value: number): number {
			return value / 7812.5;
		}
		static toGigabytes(value: number): number {
			return value / 7812500.0;
		}
		static toTerabytes(value: number): number {
			return value / 7812500000.0;
		}
		static toMebibits(value: number): number {
			return value / 1024.0;
		}
	}

	export class Kilobits {
		static toBits(value: number): number {
			return value * 1000.0;
		}
		static toMegabits(value: number): number {
			return value / 1000.0;
		}
		static toGigabits(value: number): number {
			return value / 1e+6;
		}
		static toTerabits(value: number): number {
			return value / 1e+9;
		}
		static toKilobytes(value: number): number {
			return value / 8.0;
		}
		static toMegabytes(value: number): number {
			return value / 8000.0;
		}
		static toGigabytes(value: number): number {
			return value / 8e+6;
		}
		static toTerabytes(value: number): number {
			return value / 8e+9;
		}
		static toKibibits(value: number): number {
			return value / 1.024;
		}
		static toMebibits(value: number): number {
			return value / 1048.58;
		}
	}

	export class Kilobytes {
		static toBits(value: number): number {
			return value * 8000.0;
		}
		static toKilobits(value: number): number {
			return value * 8.0;
		}
		static toMegabits(value: number): number {
			return value / 125.0;
		}
		static toGigabits(value: number): number {
			return value / 125000.0;
		}
		static toTerabits(value: number): number {
			return value / 1.25e+8;
		}
		static toMegabytes(value: number): number {
			return value / 1000.0;
		}
		static toGigabytes(value: number): number {
			return value / 1e+6;
		}
		static toTerabytes(value: number): number {
			return value / 1e+9;
		}
		static toKibibits(value: number): number {
			return value * 7.812;
		}
		static toMebibits(value: number): number {
			return value * 0.00762939;
		}
	}

	export class Mebibits {
		static toBits(value: number): number {
			return value * 1048576.0;
		}
		static toKilobits(value: number): number {
			return value * 1048.58;
		}
		static toMegabits(value: number): number {
			return value * 1.04858;
		}
		static toGigabits(value: number): number {
			return value / 954.0;
		}
		static toTerabits(value: number): number {
			return value / 953674.0;
		}
		static toKilobytes(value: number): number {
			return value / 0.00762939;
		}
		static toMegabytes(value: number): number {
			return value / 7.62939;
		}
		static toGigabytes(value: number): number {
			return value / 7629.39;
		}
		static toTerabytes(value: number): number {
			return value * 0.000000131072;
		}
		static toKibibits(value: number): number {
			return value * 1024.0;
		}
	}

	export class Megabits {
		static toBits(value: number): number {
			return value * 1e+6;
		}
		static toKilobits(value: number): number {
			return value * 1000.0;
		}
		static toGigabits(value: number): number {
			return value / 1000.0;
		}
		static toTerabits(value: number): number {
			return value / 1e+6;
		}
		static toKilobytes(value: number): number {
			return value * 125.0;
		}
		static toMegabytes(value: number): number {
			return value / 8.0;
		}
		static toGigabytes(value: number): number {
			return value / 8000.0;
		}
		static toTerabytes(value: number): number {
			return value / 8e+6;
		}
		static toKibibits(value: number): number {
			return value * 976.563;
		}
		static toMebibits(value: number): number {
			return value / 1.04858;
		}
	}

	export class Megabytes {
		static toBits(value: number): number {
			return value * 8e+6;
		}
		static toKilobits(value: number): number {
			return value * 8000.0;
		}
		static toMegabits(value: number): number {
			return value * 8.0;
		}
		static toGigabits(value: number): number {
			return value / 125.0;
		}
		static toTerabits(value: number): number {
			return value / 125000.0;
		}
		static toKilobytes(value: number): number {
			return value * 1000.0;
		}
		static toGigabytes(value: number): number {
			return value / 1000.0;
		}
		static toTerabytes(value: number): number {
			return value / 1e+6;
		}
		static toKibibits(value: number): number {
			return value * 7812.5;
		}
		static toMebibits(value: number): number {
			return value * 7.62939;
		}
	}

	export class Terabits {
		static toBits(value: number): number {
			return value * 1e+12;
		}
		static toKilobits(value: number): number {
			return value * 1e+9;
		}
		static toMegabits(value: number): number {
			return value * 1e+6;
		}
		static toGigabits(value: number): number {
			return value * 1000.0;
		}
		static toKilobytes(value: number): number {
			return value * 1.25e+8;
		}
		static toMegabytes(value: number): number {
			return value * 125000.0;
		}
		static toGigabytes(value: number): number {
			return value * 125.0;
		}
		static toTerabytes(value: number): number {
			return value / 8.0;
		}
		static toKibibits(value: number): number {
			return value * 976562500.0;
		}
		static toMebibits(value: number): number {
			return value * 953674.0;
		}
	}

	export class Terabytes {
		static toBits(value: number): number {
			return value * 8e+12;
		}
		static toKilobits(value: number): number {
			return value * 8e+9;
		}
		static toMegabits(value: number): number {
			return value * 8e+6;
		}
		static toGigabits(value: number): number {
			return value * 8000.0;
		}
		static toTerabits(value: number): number {
			return value * 8.0;
		}
		static toKilobytes(value: number): number {
			return value * 1e+9;
		}
		static toMegabytes(value: number): number {
			return value * 1e+6;
		}
		static toGigabytes(value: number): number {
			return value * 1000.0;
		}
		static toKibibits(value: number): number {
			return value * 7812500000.0;
		}
		static toMebibits(value: number): number {
			return value / 0.000000131072;
		}
	}
}
