// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

export namespace Energy {
	export class Btu {
		static toKilojoules(value: number): number {
			return value * 1.0550559;
		}
		static toKilocalories(value: number): number {
			return value / 3.9673727240424;
		}
		static toJoules(value: number): number {
			return value * 1055.06;
		}
		static toCalories(value: number): number {
			return value * 252.164;
		}
		static toUSTherms(value: number): number {
			return value / 99976.12448781215;
		}
		static toWattHours(value: number): number {
			return value * 0.293071;
		}
		static toKilowattHours(value: number): number {
			return value / 3412.14;
		}
		static toFootPounds(value: number): number {
			return value * 778.169;
		}
	}

	export class Calories {
		static toKilojoules(value: number): number {
			return value / 239.0057;
		}
		static toKilocalories(value: number): number {
			return value / 1000.0;
		}
		static toJoules(value: number): number {
			return value * 4.184;
		}
		static toBtu(value: number): number {
			return value / 252.164;
		}
		static toUSTherms(value: number): number {
			return value / 25210420.0;
		}
		static toWattHours(value: number): number {
			return value * 0.00116222;
		}
		static toKilowattHours(value: number): number {
			return value / 860421.0;
		}
		static toFootPounds(value: number): number {
			return value * 3.08596;
		}
	}

	export class ElectronVolts {
	}

	export class FootPounds {
		static toKilojoules(value: number): number {
			return value / 737.562;
		}
		static toKilocalories(value: number): number {
			return value / 3085.96;
		}
		static toJoules(value: number): number {
			return value * 1.35582;
		}
		static toBtu(value: number): number {
			return value / 778.169;
		}
		static toCalories(value: number): number {
			return value / 3.08596;
		}
		static toUSTherms(value: number): number {
			return value / 77816937.099186;
		}
		static toWattHours(value: number): number {
			return value / 2655.22;
		}
		static toKilowattHours(value: number): number {
			return value * 0.00000037662;
		}
	}

	export class Joules {
		static toKilojoules(value: number): number {
			return value / 1000.0;
		}
		static toKilocalories(value: number): number {
			return value / 4184.0;
		}
		static toBtu(value: number): number {
			return value / 1055.06;
		}
		static toCalories(value: number): number {
			return value / 4.184;
		}
		static toUSTherms(value: number): number {
			return value / 105480400.0;
		}
		static toWattHours(value: number): number {
			return value / 3600.0;
		}
		static toKilowattHours(value: number): number {
			return value / 3.6e+6;
		}
		static toFootPounds(value: number): number {
			return value / 1.35582;
		}
	}

	export class Kilocalories {
		static toKilojoules(value: number): number {
			return value * 4.184;
		}
		static toJoules(value: number): number {
			return value * 4184.0;
		}
		static toBtu(value: number): number {
			return value * 3.9673727240424;
		}
		static toCalories(value: number): number {
			return value * 1000.0;
		}
		static toUSTherms(value: number): number {
			return value / 25210.4;
		}
		static toWattHours(value: number): number {
			return value * 1.16222;
		}
		static toKilowattHours(value: number): number {
			return value / 860.421;
		}
		static toFootPounds(value: number): number {
			return value * 3085.96;
		}
	}

	export class Kilojoules {
		static toKilocalories(value: number): number {
			return value / 4.184;
		}
		static toJoules(value: number): number {
			return value * 1000.0;
		}
		static toBtu(value: number): number {
			return value / 1.0550559;
		}
		static toCalories(value: number): number {
			return value * 239.0057;
		}
		static toUSTherms(value: number): number {
			return value / 105480.04;
		}
		static toWattHours(value: number): number {
			return value / 3.6;
		}
		static toKilowattHours(value: number): number {
			return value / 3600.0;
		}
		static toFootPounds(value: number): number {
			return value * 737.562;
		}
	}

	export class KilowattHours {
		static toKilojoules(value: number): number {
			return value * 3600.0;
		}
		static toKilocalories(value: number): number {
			return value * 860.421;
		}
		static toJoules(value: number): number {
			return value * 3.6e+6;
		}
		static toBtu(value: number): number {
			return value * 3412.14;
		}
		static toCalories(value: number): number {
			return value * 860421.0;
		}
		static toUSTherms(value: number): number {
			return value / 29.3001;
		}
		static toWattHours(value: number): number {
			return value * 1000.0;
		}
		static toFootPounds(value: number): number {
			return value / 0.00000037662;
		}
	}

	export class USTherms {
		static toKilojoules(value: number): number {
			return value * 105480.04;
		}
		static toKilocalories(value: number): number {
			return value * 25210.4;
		}
		static toJoules(value: number): number {
			return value * 105480400.0;
		}
		static toBtu(value: number): number {
			return value * 99976.12448781215;
		}
		static toCalories(value: number): number {
			return value * 25210420.0;
		}
		static toWattHours(value: number): number {
			return value * 29300.1;
		}
		static toKilowattHours(value: number): number {
			return value * 29.3001;
		}
		static toFootPounds(value: number): number {
			return value * 77816937.099186;
		}
	}

	export class WattHours {
		static toKilojoules(value: number): number {
			return value * 3.6;
		}
		static toKilocalories(value: number): number {
			return value / 1.16222;
		}
		static toJoules(value: number): number {
			return value * 3600.0;
		}
		static toBtu(value: number): number {
			return value / 0.293071;
		}
		static toCalories(value: number): number {
			return value / 0.00116222;
		}
		static toUSTherms(value: number): number {
			return value / 29300.1;
		}
		static toKilowattHours(value: number): number {
			return value / 1000.0;
		}
		static toFootPounds(value: number): number {
			return value * 2655.22;
		}
	}
}
