// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

export namespace Force {
	export class Dynes {
		static toNewtons(value: number): number {
			return value / 100000.0;
		}
		static toPoundals(value: number): number {
			return value / 13825.4954376;
		}
		static toKilogramforce(value: number): number {
			return value / 980665.0;
		}
	}

	export class Kilogramforce {
		static toNewtons(value: number): number {
			return value * 9.80665;
		}
		static toDynes(value: number): number {
			return value * 980665.0;
		}
		static toPoundals(value: number): number {
			return value * 70.93163528397;
		}
	}

	export class Newtons {
		static toDynes(value: number): number {
			return value * 100000.0;
		}
		static toPoundals(value: number): number {
			return value * 7.23301;
		}
		static toKilogramforce(value: number): number {
			return value / 9.80665;
		}
	}

	export class Poundals {
		static toNewtons(value: number): number {
			return value / 7.23301;
		}
		static toDynes(value: number): number {
			return value * 13825.4954376;
		}
		static toKilogramforce(value: number): number {
			return value / 70.93163528397;
		}
	}
}
