// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

export namespace Frequency {
	export class Gigahertz {
		static toHertz(value: number): number {
			return value * 1e+9;
		}
		static toKilohertz(value: number): number {
			return value * 1e+6;
		}
		static toMegahertz(value: number): number {
			return value * 1000.0;
		}
	}

	export class Hertz {
		static toKilohertz(value: number): number {
			return value / 1000.0;
		}
		static toMegahertz(value: number): number {
			return value / 1e+6;
		}
		static toGigahertz(value: number): number {
			return value / 1e+9;
		}
	}

	export class Kilohertz {
		static toHertz(value: number): number {
			return value * 1000.0;
		}
		static toMegahertz(value: number): number {
			return value / 1000.0;
		}
		static toGigahertz(value: number): number {
			return value / 1e+6;
		}
	}

	export class Megahertz {
		static toHertz(value: number): number {
			return value * 1e+6;
		}
		static toKilohertz(value: number): number {
			return value * 1000.0;
		}
		static toGigahertz(value: number): number {
			return value / 1000.0;
		}
	}
}
