// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

export namespace LuminousEnergy {
	export class LumenHour {
		static toTalbot(value: number): number {
			return value * 3600.0;
		}
		static toLumenMinute(value: number): number {
			return value * 60.0;
		}
		static toLumenSecond(value: number): number {
			return value * 3600.0;
		}
	}

	export class LumenMinute {
		static toTalbot(value: number): number {
			return value * 60.0;
		}
		static toLumenHour(value: number): number {
			return value / 60.0;
		}
		static toLumenSecond(value: number): number {
			return value * 60.0;
		}
	}

	export class LumenSecond {
		static toTalbot(value: number): number {
			return value;
		}
		static toLumenHour(value: number): number {
			return value / 3600.0;
		}
		static toLumenMinute(value: number): number {
			return value / 60.0;
		}
	}

	export class Talbot {
		static toLumenSecond(value: number): number {
			return value;
		}
		static toLumenHour(value: number): number {
			return value / 3600.0;
		}
		static toLumenMinute(value: number): number {
			return value / 60.0;
		}
	}
}
