// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

export namespace MagnetomotiveForce {
	export class Ampereturns {
		static toGilberts(value: number): number {
			return value * 1.256637061436;
		}
	}

	export class Gilberts {
		static toAmpereturns(value: number): number {
			return value * 0.7957747154595;
		}
	}
}
