// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

export namespace Mass {
	export class Grams {
		static toMilligrams(value: number): number {
			return value * 1000.0;
		}
		static toKilograms(value: number): number {
			return value / 1000.0;
		}
		static toTonnes(value: number): number {
			return value * 1e-6;
		}
		static toOunces(value: number): number {
			return value / 28.3495231;
		}
		static toPounds(value: number): number {
			return value / 453.59237;
		}
		static toStones(value: number): number {
			return value / 6350.29318;
		}
	}

	export class Kilograms {
		static toMilligrams(value: number): number {
			return value * 1e+6;
		}
		static toGrams(value: number): number {
			return value * 1000.0;
		}
		static toTonnes(value: number): number {
			return value * 0.001;
		}
		static toOunces(value: number): number {
			return value * 35.274;
		}
		static toPounds(value: number): number {
			return value * 2.20462;
		}
		static toStones(value: number): number {
			return value / 6.35029;
		}
	}

	export class Milligrams {
		static toGrams(value: number): number {
			return value / 1000.0;
		}
		static toKilograms(value: number): number {
			return value / 1e+6;
		}
		static toTonnes(value: number): number {
			return value / 1e+9;
		}
		static toOunces(value: number): number {
			return value / 28349.5231;
		}
		static toPounds(value: number): number {
			return value / 453592.37;
		}
		static toStones(value: number): number {
			return value / 6350293.18;
		}
	}

	export class Ounces {
		static toMilligrams(value: number): number {
			return value * 28349.5231;
		}
		static toGrams(value: number): number {
			return value * 28.3495231;
		}
		static toKilograms(value: number): number {
			return value / 35.274;
		}
		static toTonnes(value: number): number {
			return value * 0.0000283495231;
		}
		static toPounds(value: number): number {
			return value * 0.0625;
		}
		static toStones(value: number): number {
			return value / 224.0;
		}
	}

	export class Pounds {
		static toMilligrams(value: number): number {
			return value * 453592.37;
		}
		static toGrams(value: number): number {
			return value * 453.59237;
		}
		static toKilograms(value: number): number {
			return value / 2.20462;
		}
		static toTonnes(value: number): number {
			return value / 2204.62;
		}
		static toOunces(value: number): number {
			return value * 16.0;
		}
		static toStones(value: number): number {
			return value / 14.0;
		}
	}

	export class Stones {
		static toMilligrams(value: number): number {
			return value * 6350293.18;
		}
		static toGrams(value: number): number {
			return value * 6350.29318;
		}
		static toKilograms(value: number): number {
			return value * 6.35029;
		}
		static toTonnes(value: number): number {
			return value / 157.473;
		}
		static toOunces(value: number): number {
			return value * 224.0;
		}
		static toPounds(value: number): number {
			return value * 14.0;
		}
	}

	export class Tonnes {
		static toMilligrams(value: number): number {
			return value * 1e+9;
		}
		static toGrams(value: number): number {
			return value * 1e+6;
		}
		static toKilograms(value: number): number {
			return value * 1000.0;
		}
		static toOunces(value: number): number {
			return value / 0.0000283495231;
		}
		static toPounds(value: number): number {
			return value * 2204.62;
		}
		static toStones(value: number): number {
			return value * 157.473;
		}
	}
}
