// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

export namespace Power {
	export class MechanicalHorsePower {
		static toMetricHorsePower(value: number): number {
			return value * 1.013869665424;
		}
	}

	export class MetricHorsePower {
		static toMechanicalHorsePower(value: number): number {
			return value / 1.013869665424;
		}
	}
}
