// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

export namespace Speed {
	export class FeetPerSecond {
		static toMilesPerHour(value: number): number {
			return value * 0.681818;
		}
		static toKilometresPerHour(value: number): number {
			return value * 1.09728;
		}
		static toMetresPerSecond(value: number): number {
			return value * 0.3048;
		}
		static toKnots(value: number): number {
			return value * 0.592484;
		}
	}

	export class KilometresPerHour {
		static toMilesPerHour(value: number): number {
			return value * 0.621371;
		}
		static toFeetPerSecond(value: number): number {
			return value * 0.911344;
		}
		static toMetresPerSecond(value: number): number {
			return value * 0.277778;
		}
		static toKnots(value: number): number {
			return value * 0.539957;
		}
	}

	export class Knots {
		static toMilesPerHour(value: number): number {
			return value * 1.15078;
		}
		static toKilometresPerHour(value: number): number {
			return value * 1.852;
		}
		static toFeetPerSecond(value: number): number {
			return value * 1.68781;
		}
		static toMetresPerSecond(value: number): number {
			return value * 0.514444;
		}
	}

	export class MetresPerSecond {
		static toMilesPerHour(value: number): number {
			return value * 2.23694;
		}
		static toKilometresPerHour(value: number): number {
			return value * 3.6;
		}
		static toFeetPerSecond(value: number): number {
			return value * 3.28084;
		}
		static toKnots(value: number): number {
			return value * 1.94384;
		}
	}

	export class MilesPerHour {
		static toKilometresPerHour(value: number): number {
			return value * 1.60934;
		}
		static toFeetPerSecond(value: number): number {
			return value * 1.46667;
		}
		static toMetresPerSecond(value: number): number {
			return value * 0.44704;
		}
		static toKnots(value: number): number {
			return value * 0.868976;
		}
	}
}
