// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

export namespace Time {
	export class Centuries {
		static toSeconds(value: number): number {
			return value * 3.154e+9;
		}
		static toMinutes(value: number): number {
			return value * 5.256e+7;
		}
		static toHours(value: number): number {
			return value * 876000.0;
		}
		static toDays(value: number): number {
			return value * 36500.0;
		}
		static toWeeks(value: number): number {
			return value * 5214.29;
		}
		static toMonths(value: number): number {
			return value * 1200.0;
		}
		static toYears(value: number): number {
			return value * 100.0;
		}
		static toDecades(value: number): number {
			return value * 10.0;
		}
	}

	export class Days {
		static toSeconds(value: number): number {
			return value * 86400.0;
		}
		static toMinutes(value: number): number {
			return value * 1440.0;
		}
		static toHours(value: number): number {
			return value * 24.0;
		}
		static toWeeks(value: number): number {
			return value / 7.0;
		}
		static toMonths(value: number): number {
			return value / 30.4167;
		}
		static toYears(value: number): number {
			return value / 365.0;
		}
		static toDecades(value: number): number {
			return value / 3650.0;
		}
		static toCenturies(value: number): number {
			return value / 36500.0;
		}
	}

	export class Decades {
		static toSeconds(value: number): number {
			return value * 3.154e+8;
		}
		static toMinutes(value: number): number {
			return value * 5.256e+6;
		}
		static toHours(value: number): number {
			return value * 87600.0;
		}
		static toDays(value: number): number {
			return value * 3650.0;
		}
		static toWeeks(value: number): number {
			return value * 521.429;
		}
		static toMonths(value: number): number {
			return value * 120.0;
		}
		static toYears(value: number): number {
			return value * 10.0;
		}
		static toCenturies(value: number): number {
			return value / 10.0;
		}
	}

	export class Hours {
		static toSeconds(value: number): number {
			return value * 3600.0;
		}
		static toMinutes(value: number): number {
			return value * 60.0;
		}
		static toDays(value: number): number {
			return value / 24.0;
		}
		static toWeeks(value: number): number {
			return value / 168.0;
		}
		static toMonths(value: number): number {
			return value / 730.001;
		}
		static toYears(value: number): number {
			return value / 8760.0;
		}
		static toDecades(value: number): number {
			return value / 87600.0;
		}
		static toCenturies(value: number): number {
			return value / 876000.0;
		}
	}

	export class Minutes {
		static toSeconds(value: number): number {
			return value * 60.0;
		}
		static toHours(value: number): number {
			return value / 60.0;
		}
		static toDays(value: number): number {
			return value / 1440.0;
		}
		static toWeeks(value: number): number {
			return value / 10080.0;
		}
		static toMonths(value: number): number {
			return value / 43800.0;
		}
		static toYears(value: number): number {
			return value / 525600.0;
		}
		static toDecades(value: number): number {
			return value / 5.256e+6;
		}
		static toCenturies(value: number): number {
			return value / 5.256e+7;
		}
	}

	export class Months {
		static toSeconds(value: number): number {
			return value * 2.628e+6;
		}
		static toMinutes(value: number): number {
			return value * 43800.0;
		}
		static toHours(value: number): number {
			return value * 730.001;
		}
		static toDays(value: number): number {
			return value * 30.4167;
		}
		static toWeeks(value: number): number {
			return value * 4.34524;
		}
		static toYears(value: number): number {
			return value / 12.0;
		}
		static toDecades(value: number): number {
			return value / 120.0;
		}
		static toCenturies(value: number): number {
			return value / 1200.0;
		}
	}

	export class Seconds {
		static toMinutes(value: number): number {
			return value / 60.0;
		}
		static toHours(value: number): number {
			return value / 3600.0;
		}
		static toDays(value: number): number {
			return value / 86400.0;
		}
		static toWeeks(value: number): number {
			return value / 604800.0;
		}
		static toMonths(value: number): number {
			return value / 2.628e+6;
		}
		static toYears(value: number): number {
			return value / 3.1536e+7;
		}
		static toDecades(value: number): number {
			return value / 3.154e+8;
		}
		static toCenturies(value: number): number {
			return value / 3.154e+9;
		}
	}

	export class Weeks {
		static toSeconds(value: number): number {
			return value * 604800.0;
		}
		static toMinutes(value: number): number {
			return value * 10080.0;
		}
		static toHours(value: number): number {
			return value * 168.0;
		}
		static toDays(value: number): number {
			return value * 7.0;
		}
		static toMonths(value: number): number {
			return value / 4.34524;
		}
		static toYears(value: number): number {
			return value / 52.143;
		}
		static toDecades(value: number): number {
			return value / 521.429;
		}
		static toCenturies(value: number): number {
			return value / 5214.29;
		}
	}

	export class Years {
		static toSeconds(value: number): number {
			return value * 3.1536e+7;
		}
		static toMinutes(value: number): number {
			return value * 525600.0;
		}
		static toHours(value: number): number {
			return value * 8760.0;
		}
		static toDays(value: number): number {
			return value * 365.0;
		}
		static toWeeks(value: number): number {
			return value * 52.143;
		}
		static toMonths(value: number): number {
			return value * 12.0;
		}
		static toDecades(value: number): number {
			return value / 10.0;
		}
		static toCenturies(value: number): number {
			return value / 100.0;
		}
	}
}
