// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

export namespace Time {
	export class Centuries {
		static toNanoseconds(value: number): number {
			return value * 3.154e+18;
		}
		static toMicroseconds(value: number): number {
			return value * 3.154e+15;
		}
		static toMilliseconds(value: number): number {
			return value * 3.154e+12;
		}
		static toSeconds(value: number): number {
			return value * 3.154e+9;
		}
		static toMinutes(value: number): number {
			return value * 5.256e+7;
		}
		static toHours(value: number): number {
			return value * 876000.0;
		}
		static toDays(value: number): number {
			return value * 36500.0;
		}
		static toWeeks(value: number): number {
			return value * 5214.29;
		}
		static toMonths(value: number): number {
			return value * 1200.0;
		}
		static toYears(value: number): number {
			return value * 100.0;
		}
		static toDecades(value: number): number {
			return value * 10.0;
		}
	}

	export class Days {
		static toNanoseconds(value: number): number {
			return value * 8.64e+13;
		}
		static toMicroseconds(value: number): number {
			return value * 8.64e+10;
		}
		static toMilliseconds(value: number): number {
			return value * 8.64e+7;
		}
		static toSeconds(value: number): number {
			return value * 86400.0;
		}
		static toMinutes(value: number): number {
			return value * 1440.0;
		}
		static toHours(value: number): number {
			return value * 24.0;
		}
		static toWeeks(value: number): number {
			return value / 7.0;
		}
		static toMonths(value: number): number {
			return value / 30.4167;
		}
		static toYears(value: number): number {
			return value / 365.0;
		}
		static toDecades(value: number): number {
			return value / 3650.0;
		}
		static toCenturies(value: number): number {
			return value / 36500.0;
		}
	}

	export class Decades {
		static toNanoseconds(value: number): number {
			return value * 3.154e+17;
		}
		static toMicroseconds(value: number): number {
			return value * 3.154e+14;
		}
		static toMilliseconds(value: number): number {
			return value * 3.154e+11;
		}
		static toSeconds(value: number): number {
			return value * 3.154e+8;
		}
		static toMinutes(value: number): number {
			return value * 5.256e+6;
		}
		static toHours(value: number): number {
			return value * 87600.0;
		}
		static toDays(value: number): number {
			return value * 3650.0;
		}
		static toWeeks(value: number): number {
			return value * 521.429;
		}
		static toMonths(value: number): number {
			return value * 120.0;
		}
		static toYears(value: number): number {
			return value * 10.0;
		}
		static toCenturies(value: number): number {
			return value / 10.0;
		}
	}

	export class Hours {
		static toNanoseconds(value: number): number {
			return value * 3.6e+12;
		}
		static toMicroseconds(value: number): number {
			return value * 3.6e+9;
		}
		static toMilliseconds(value: number): number {
			return value * 3.6e+6;
		}
		static toSeconds(value: number): number {
			return value * 3600.0;
		}
		static toMinutes(value: number): number {
			return value * 60.0;
		}
		static toDays(value: number): number {
			return value / 24.0;
		}
		static toWeeks(value: number): number {
			return value / 168.0;
		}
		static toMonths(value: number): number {
			return value / 730.001;
		}
		static toYears(value: number): number {
			return value / 8760.0;
		}
		static toDecades(value: number): number {
			return value / 87600.0;
		}
		static toCenturies(value: number): number {
			return value / 876000.0;
		}
	}

	export class Microseconds {
		static toNanoseconds(value: number): number {
			return value * 1000.0;
		}
		static toMilliseconds(value: number): number {
			return value / 1000.0;
		}
		static toSeconds(value: number): number {
			return value / 1e+6;
		}
		static toMinutes(value: number): number {
			return value / 6e+7;
		}
		static toHours(value: number): number {
			return value / 3.6e+9;
		}
		static toDays(value: number): number {
			return value / 8.64e+10;
		}
		static toWeeks(value: number): number {
			return value / 6.048e+11;
		}
		static toMonths(value: number): number {
			return value / 2629746000000.0;
		}
		static toYears(value: number): number {
			return value / 3.154e+13;
		}
		static toDecades(value: number): number {
			return value / 3.154e+14;
		}
		static toCenturies(value: number): number {
			return value / 3.154e+15;
		}
	}

	export class Milliseconds {
		static toNanoseconds(value: number): number {
			return value * 1e+6;
		}
		static toMicroseconds(value: number): number {
			return value * 1000.0;
		}
		static toSeconds(value: number): number {
			return value / 1000.0;
		}
		static toMinutes(value: number): number {
			return value / 60000.0;
		}
		static toHours(value: number): number {
			return value / 3.6e+6;
		}
		static toDays(value: number): number {
			return value / 8.64e+7;
		}
		static toWeeks(value: number): number {
			return value / 6.048e+8;
		}
		static toMonths(value: number): number {
			return value / 2629746000.0;
		}
		static toYears(value: number): number {
			return value / 31556952000.0;
		}
		static toDecades(value: number): number {
			return value / 3.154e+11;
		}
		static toCenturies(value: number): number {
			return value / 3.154e+12;
		}
	}

	export class Minutes {
		static toNanoseconds(value: number): number {
			return value * 6e+10;
		}
		static toMicroseconds(value: number): number {
			return value * 6e+7;
		}
		static toMilliseconds(value: number): number {
			return value * 60000.0;
		}
		static toSeconds(value: number): number {
			return value * 60.0;
		}
		static toHours(value: number): number {
			return value / 60.0;
		}
		static toDays(value: number): number {
			return value / 1440.0;
		}
		static toWeeks(value: number): number {
			return value / 10080.0;
		}
		static toMonths(value: number): number {
			return value / 43800.0;
		}
		static toYears(value: number): number {
			return value / 525600.0;
		}
		static toDecades(value: number): number {
			return value / 5.256e+6;
		}
		static toCenturies(value: number): number {
			return value / 5.256e+7;
		}
	}

	export class Months {
		static toNanoseconds(value: number): number {
			return value * 2629746000000000.0;
		}
		static toMicroseconds(value: number): number {
			return value * 2629746000000.0;
		}
		static toMilliseconds(value: number): number {
			return value * 2629746000.0;
		}
		static toSeconds(value: number): number {
			return value * 2.628e+6;
		}
		static toMinutes(value: number): number {
			return value * 43800.0;
		}
		static toHours(value: number): number {
			return value * 730.001;
		}
		static toDays(value: number): number {
			return value * 30.4167;
		}
		static toWeeks(value: number): number {
			return value * 4.34524;
		}
		static toYears(value: number): number {
			return value / 12.0;
		}
		static toDecades(value: number): number {
			return value / 120.0;
		}
		static toCenturies(value: number): number {
			return value / 1200.0;
		}
	}

	export class Nanoseconds {
		static toMicroseconds(value: number): number {
			return value / 1000.0;
		}
		static toMilliseconds(value: number): number {
			return value / 1e+6;
		}
		static toSeconds(value: number): number {
			return value / 1e+9;
		}
		static toMinutes(value: number): number {
			return value / 6e+10;
		}
		static toHours(value: number): number {
			return value / 3.6e+12;
		}
		static toDays(value: number): number {
			return value / 8.64e+13;
		}
		static toWeeks(value: number): number {
			return value / 6.048e+14;
		}
		static toMonths(value: number): number {
			return value / 2629746000000000.0;
		}
		static toYears(value: number): number {
			return value / 3.154e+16;
		}
		static toDecades(value: number): number {
			return value / 3.154e+17;
		}
		static toCenturies(value: number): number {
			return value / 3.154e+18;
		}
	}

	export class Seconds {
		static toNanoseconds(value: number): number {
			return value * 1e+9;
		}
		static toMicroseconds(value: number): number {
			return value * 1e+6;
		}
		static toMilliseconds(value: number): number {
			return value * 1000.0;
		}
		static toMinutes(value: number): number {
			return value / 60.0;
		}
		static toHours(value: number): number {
			return value / 3600.0;
		}
		static toDays(value: number): number {
			return value / 86400.0;
		}
		static toWeeks(value: number): number {
			return value / 604800.0;
		}
		static toMonths(value: number): number {
			return value / 2.628e+6;
		}
		static toYears(value: number): number {
			return value / 3.1536e+7;
		}
		static toDecades(value: number): number {
			return value / 3.154e+8;
		}
		static toCenturies(value: number): number {
			return value / 3.154e+9;
		}
	}

	export class Weeks {
		static toNanoseconds(value: number): number {
			return value * 6.048e+14;
		}
		static toMicroseconds(value: number): number {
			return value * 6.048e+11;
		}
		static toMilliseconds(value: number): number {
			return value * 6.048e+8;
		}
		static toSeconds(value: number): number {
			return value * 604800.0;
		}
		static toMinutes(value: number): number {
			return value * 10080.0;
		}
		static toHours(value: number): number {
			return value * 168.0;
		}
		static toDays(value: number): number {
			return value * 7.0;
		}
		static toMonths(value: number): number {
			return value / 4.34524;
		}
		static toYears(value: number): number {
			return value / 52.143;
		}
		static toDecades(value: number): number {
			return value / 521.429;
		}
		static toCenturies(value: number): number {
			return value / 5214.29;
		}
	}

	export class Years {
		static toNanoseconds(value: number): number {
			return value * 3.154e+16;
		}
		static toMicroseconds(value: number): number {
			return value * 3.154e+13;
		}
		static toMilliseconds(value: number): number {
			return value * 31556952000.0;
		}
		static toSeconds(value: number): number {
			return value * 3.1536e+7;
		}
		static toMinutes(value: number): number {
			return value * 525600.0;
		}
		static toHours(value: number): number {
			return value * 8760.0;
		}
		static toDays(value: number): number {
			return value * 365.0;
		}
		static toWeeks(value: number): number {
			return value * 52.143;
		}
		static toMonths(value: number): number {
			return value * 12.0;
		}
		static toDecades(value: number): number {
			return value / 10.0;
		}
		static toCenturies(value: number): number {
			return value / 100.0;
		}
	}
}
