// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

export namespace Volume {
	export class CubicFeet {
		static toMillilitres(value: number): number {
			return value * 28316.8;
		}
		static toLitres(value: number): number {
			return value * 28.3168;
		}
		static toKilolitres(value: number): number {
			return value / 35.3147;
		}
		static toTeaspoons(value: number): number {
			return value * 4783.74;
		}
		static toTablespoons(value: number): number {
			return value * 1594.58;
		}
		static toQuarts(value: number): number {
			return value * 24.9153;
		}
		static toPints(value: number): number {
			return value * 49.8307;
		}
		static toGallons(value: number): number {
			return value * 6.22884;
		}
		static toFluidOunces(value: number): number {
			return value * 996.614;
		}
		static toUSTeaspoons(value: number): number {
			return value * 5745.04;
		}
		static toUSTablespoons(value: number): number {
			return value * 1915.01;
		}
		static toUSQuarts(value: number): number {
			return value * 29.9221;
		}
		static toUSPints(value: number): number {
			return value * 59.8442;
		}
		static toUSGallons(value: number): number {
			return value * 7.48052;
		}
		static toUSFluidOunces(value: number): number {
			return value * 957.506;
		}
		static toUSCups(value: number): number {
			return value * 117.987;
		}
		static toCubicMetres(value: number): number {
			return value / 35.3147;
		}
		static toCubicInches(value: number): number {
			return value * 1728.0;
		}
		static toOilBarrels(value: number): number {
			return value / 5.61458;
		}
	}

	export class CubicInches {
		static toMillilitres(value: number): number {
			return value * 16.3871;
		}
		static toLitres(value: number): number {
			return value / 61.0237;
		}
		static toKilolitres(value: number): number {
			return value / 61023.7;
		}
		static toTeaspoons(value: number): number {
			return value * 2.76837;
		}
		static toTablespoons(value: number): number {
			return value / 1.08367;
		}
		static toQuarts(value: number): number {
			return value / 69.3549;
		}
		static toPints(value: number): number {
			return value / 34.6774;
		}
		static toGallons(value: number): number {
			return value / 277.419;
		}
		static toFluidOunces(value: number): number {
			return value / 1.73387;
		}
		static toUSTeaspoons(value: number): number {
			return value * 3.32468;
		}
		static toUSTablespoons(value: number): number {
			return value * 1.10823;
		}
		static toUSQuarts(value: number): number {
			return value / 57.75;
		}
		static toUSPints(value: number): number {
			return value / 28.875;
		}
		static toUSGallons(value: number): number {
			return value / 231.0;
		}
		static toUSFluidOunces(value: number): number {
			return value / 1.80469;
		}
		static toUSCups(value: number): number {
			return value / 14.6457;
		}
		static toCubicMetres(value: number): number {
			return value / 61023.7;
		}
		static toCubicFeet(value: number): number {
			return value / 1728.0;
		}
		static toOilBarrels(value: number): number {
			return value / 9702.0;
		}
	}

	export class CubicMetres {
		static toMillilitres(value: number): number {
			return value * 1000000.0;
		}
		static toLitres(value: number): number {
			return value * 1000.0;
		}
		static toKilolitres(value: number): number {
			return value * 1.0;
		}
		static toTeaspoons(value: number): number {
			return value * 168936.0;
		}
		static toTablespoons(value: number): number {
			return value * 56312.1;
		}
		static toQuarts(value: number): number {
			return value * 879.877;
		}
		static toPints(value: number): number {
			return value * 1759.75;
		}
		static toGallons(value: number): number {
			return value * 219.969;
		}
		static toFluidOunces(value: number): number {
			return value * 35195.1;
		}
		static toUSTeaspoons(value: number): number {
			return value * 202884.0;
		}
		static toUSTablespoons(value: number): number {
			return value * 67628.0;
		}
		static toUSQuarts(value: number): number {
			return value * 1056.69;
		}
		static toUSPints(value: number): number {
			return value * 2113.38;
		}
		static toUSGallons(value: number): number {
			return value * 264.172;
		}
		static toUSFluidOunces(value: number): number {
			return value * 33814.0;
		}
		static toUSCups(value: number): number {
			return value * 4166.67;
		}
		static toCubicFeet(value: number): number {
			return value * 35.3147;
		}
		static toCubicInches(value: number): number {
			return value * 61023.7;
		}
		static toOilBarrels(value: number): number {
			return value * 6.28981;
		}
	}

	export class FluidOunces {
		static toMillilitres(value: number): number {
			return value * 28.413074243749994496;
		}
		static toLitres(value: number): number {
			return value * 0.028413074243749994496;
		}
		static toKilolitres(value: number): number {
			return value * 0.000028413074243749994;
		}
		static toTeaspoons(value: number): number {
			return value * 4.8;
		}
		static toTablespoons(value: number): number {
			return value * 1.6;
		}
		static toQuarts(value: number): number {
			return value / 40.0;
		}
		static toPints(value: number): number {
			return value / 20.0;
		}
		static toGallons(value: number): number {
			return value / 160.0;
		}
		static toUSTeaspoons(value: number): number {
			return value / 0.1734737167638313984;
		}
		static toUSTablespoons(value: number): number {
			return value / 0.52042115029149417472;
		}
		static toUSQuarts(value: number): number {
			return value / 33.306953618655629312;
		}
		static toUSPints(value: number): number {
			return value / 16.653476809327814656;
		}
		static toUSGallons(value: number): number {
			return value / 133.22781447462252544;
		}
		static toUSFluidOunces(value: number): number {
			return value / 1.0408423005829883904;
		}
		static toUSCups(value: number): number {
			return value / 8.3267384046639071232;
		}
		static toCubicMetres(value: number): number {
			return value / 35195.1;
		}
		static toCubicFeet(value: number): number {
			return value / 996.614;
		}
		static toCubicInches(value: number): number {
			return value * 1.73387;
		}
		static toOilBarrels(value: number): number {
			return value / 5595.57;
		}
	}

	export class Gallons {
		static toMillilitres(value: number): number {
			return value * 4546.091879;
		}
		static toLitres(value: number): number {
			return value * 4.546091879;
		}
		static toKilolitres(value: number): number {
			return value * 0.0045460918799;
		}
		static toTeaspoons(value: number): number {
			return value * 768.0;
		}
		static toTablespoons(value: number): number {
			return value * 256.0;
		}
		static toQuarts(value: number): number {
			return value * 4.0;
		}
		static toPints(value: number): number {
			return value * 8.0;
		}
		static toFluidOunces(value: number): number {
			return value * 160.0;
		}
		static toUSTeaspoons(value: number): number {
			return value / 0.00108421072977394606;
		}
		static toUSTablespoons(value: number): number {
			return value / 0.003252632189321838592;
		}
		static toUSQuarts(value: number): number {
			return value / 0.20816846011659767808;
		}
		static toUSPints(value: number): number {
			return value / 0.10408423005829883904;
		}
		static toUSGallons(value: number): number {
			return value / 0.83267384046639071232;
		}
		static toUSFluidOunces(value: number): number {
			return value / 0.006505264378643677184;
		}
		static toUSCups(value: number): number {
			return value / 0.052042115029149417472;
		}
		static toCubicMetres(value: number): number {
			return value / 219.969;
		}
		static toCubicFeet(value: number): number {
			return value / 6.22884;
		}
		static toCubicInches(value: number): number {
			return value * 277.419;
		}
		static toOilBarrels(value: number): number {
			return value / 34.9723;
		}
	}

	export class Kilolitres {
		static toMillilitres(value: number): number {
			return value * 1000000.0;
		}
		static toLitres(value: number): number {
			return value * 1000.0;
		}
		static toTeaspoons(value: number): number {
			return value / 0.000005919390467447916;
		}
		static toTablespoons(value: number): number {
			return value / 0.000017758171402343747;
		}
		static toQuarts(value: number): number {
			return value / 0.00113652296975;
		}
		static toPints(value: number): number {
			return value / 0.000568261484874999889;
		}
		static toGallons(value: number): number {
			return value / 0.0045460918799;
		}
		static toFluidOunces(value: number): number {
			return value / 0.0000284130742437499946;
		}
		static toUSTeaspoons(value: number): number {
			return value / 0.000004928921593749999;
		}
		static toUSTablespoons(value: number): number {
			return value / 0.000014786764781249998;
		}
		static toUSQuarts(value: number): number {
			return value / 0.000946352945999999959;
		}
		static toUSPints(value: number): number {
			return value / 0.000473176472999999979;
		}
		static toUSGallons(value: number): number {
			return value / 0.003785411784;
		}
		static toUSFluidOunces(value: number): number {
			return value / 0.0000295735296;
		}
		static toUSCups(value: number): number {
			return value / 0.000236588236499999989;
		}
		static toCubicMetres(value: number): number {
			return value * 1.0;
		}
		static toCubicFeet(value: number): number {
			return value * 35.3147;
		}
		static toCubicInches(value: number): number {
			return value * 61023.7;
		}
		static toOilBarrels(value: number): number {
			return value * 6.28981;
		}
	}

	export class Litres {
		static toMillilitres(value: number): number {
			return value * 1000.0;
		}
		static toKilolitres(value: number): number {
			return value / 1000.0;
		}
		static toTeaspoons(value: number): number {
			return value / 0.005919390467447916134;
		}
		static toTablespoons(value: number): number {
			return value / 0.017758171402343747584;
		}
		static toQuarts(value: number): number {
			return value / 1.13652296975;
		}
		static toPints(value: number): number {
			return value / 0.56826148487499988992;
		}
		static toGallons(value: number): number {
			return value / 4.546091879;
		}
		static toFluidOunces(value: number): number {
			return value / 0.028413074243749994496;
		}
		static toUSTeaspoons(value: number): number {
			return value / 0.004928921593749999616;
		}
		static toUSTablespoons(value: number): number {
			return value / 0.014786764781249998848;
		}
		static toUSQuarts(value: number): number {
			return value / 0.94635294599999995904;
		}
		static toUSPints(value: number): number {
			return value / 0.47317647299999997952;
		}
		static toUSGallons(value: number): number {
			return value / 3.785411784;
		}
		static toUSFluidOunces(value: number): number {
			return value / 0.029573529562499997696;
		}
		static toUSCups(value: number): number {
			return value / 0.23658823649999998976;
		}
		static toCubicMetres(value: number): number {
			return value / 1000.0;
		}
		static toCubicFeet(value: number): number {
			return value / 28.3168;
		}
		static toCubicInches(value: number): number {
			return value * 61.0237;
		}
		static toOilBarrels(value: number): number {
			return value / 158.987;
		}
	}

	export class Millilitres {
		static toLitres(value: number): number {
			return value / 1000.0;
		}
		static toKilolitres(value: number): number {
			return value / 1000000.0;
		}
		static toTeaspoons(value: number): number {
			return value / 5.9193904674479161344;
		}
		static toTablespoons(value: number): number {
			return value / 17.758171402343747584;
		}
		static toQuarts(value: number): number {
			return value / 1136.52296975;
		}
		static toPints(value: number): number {
			return value / 568.26148487499988992;
		}
		static toGallons(value: number): number {
			return value / 4546.091879;
		}
		static toFluidOunces(value: number): number {
			return value / 28.413074243749994496;
		}
		static toUSTeaspoons(value: number): number {
			return value / 4.928921593749999616;
		}
		static toUSTablespoons(value: number): number {
			return value / 14.786764781249998848;
		}
		static toUSQuarts(value: number): number {
			return value / 946.35294599999995904;
		}
		static toUSPints(value: number): number {
			return value / 473.17647299999997952;
		}
		static toUSGallons(value: number): number {
			return value / 3785.411784;
		}
		static toUSFluidOunces(value: number): number {
			return value / 29.573529562499997696;
		}
		static toUSCups(value: number): number {
			return value / 236.58823649999998976;
		}
		static toCubicMetres(value: number): number {
			return value / 1000000.0;
		}
		static toCubicFeet(value: number): number {
			return value / 28316.8;
		}
		static toCubicInches(value: number): number {
			return value / 16.3871;
		}
		static toOilBarrels(value: number): number {
			return value / 158987.0;
		}
	}

	export class OilBarrels {
		static toMillilitres(value: number): number {
			return value * 158987.0;
		}
		static toLitres(value: number): number {
			return value * 158.987;
		}
		static toKilolitres(value: number): number {
			return value / 6.28981;
		}
		static toTeaspoons(value: number): number {
			return value * 26858.7;
		}
		static toTablespoons(value: number): number {
			return value * 8952.91;
		}
		static toQuarts(value: number): number {
			return value * 139.889;
		}
		static toPints(value: number): number {
			return value * 279.779;
		}
		static toGallons(value: number): number {
			return value * 34.9723;
		}
		static toFluidOunces(value: number): number {
			return value * 5595.57;
		}
		static toUSTeaspoons(value: number): number {
			return value * 32256.0;
		}
		static toUSTablespoons(value: number): number {
			return value * 10752.0;
		}
		static toUSQuarts(value: number): number {
			return value * 168.0;
		}
		static toUSPints(value: number): number {
			return value * 336.0;
		}
		static toUSGallons(value: number): number {
			return value * 42.0;
		}
		static toUSFluidOunces(value: number): number {
			return value * 5376.0;
		}
		static toUSCups(value: number): number {
			return value * 662.447;
		}
		static toCubicMetres(value: number): number {
			return value / 6.28981;
		}
		static toCubicFeet(value: number): number {
			return value * 5.61458;
		}
		static toCubicInches(value: number): number {
			return value * 9702.0;
		}
	}

	export class Pints {
		static toMillilitres(value: number): number {
			return value * 568.26148487499988992;
		}
		static toLitres(value: number): number {
			return value * 0.56826148487499988992;
		}
		static toKilolitres(value: number): number {
			return value * 0.000568261484874999889;
		}
		static toTeaspoons(value: number): number {
			return value * 96.0;
		}
		static toTablespoons(value: number): number {
			return value * 32.0;
		}
		static toQuarts(value: number): number {
			return value  / 2.0;
		}
		static toGallons(value: number): number {
			return value / 8.0;
		}
		static toFluidOunces(value: number): number {
			return value * 20.0;
		}
		static toUSTeaspoons(value: number): number {
			return value / 0.008673685838191568486;
		}
		static toUSTablespoons(value: number): number {
			return value / 0.026021057514574708736;
		}
		static toUSQuarts(value: number): number {
			return value / 1.6653476809327814656;
		}
		static toUSPints(value: number): number {
			return value / 0.83267384046639071232;
		}
		static toUSGallons(value: number): number {
			return value / 6.6613907237311258624;
		}
		static toUSFluidOunces(value: number): number {
			return value / 0.052042115029149417472;
		}
		static toUSCups(value: number): number {
			return value / 0.41633692023319535616;
		}
		static toCubicMetres(value: number): number {
			return value / 1759.75;
		}
		static toCubicFeet(value: number): number {
			return value / 49.8307;
		}
		static toCubicInches(value: number): number {
			return value * 34.6774;
		}
		static toOilBarrels(value: number): number {
			return value / 279.779;
		}
	}

	export class Quarts {
		static toMillilitres(value: number): number {
			return value * 1136.52296975;
		}
		static toLitres(value: number): number {
			return value * 1.13652296975;
		}
		static toKilolitres(value: number): number {
			return value * 0.00113652296975;
		}
		static toTeaspoons(value: number): number {
			return value * 192.0;
		}
		static toTablespoons(value: number): number {
			return value * 64.0;
		}
		static toPints(value: number): number {
			return value * 2.0;
		}
		static toGallons(value: number): number {
			return value / 4.0;
		}
		static toFluidOunces(value: number): number {
			return value * 40.0;
		}
		static toUSTeaspoons(value: number): number {
			return value / 0.004336842919095784243;
		}
		static toUSTablespoons(value: number): number {
			return value / 0.013010528757287354368;
		}
		static toUSQuarts(value: number): number {
			return value / 0.83267384046639071232;
		}
		static toUSPints(value: number): number {
			return value / 0.41633692023319535616;
		}
		static toUSGallons(value: number): number {
			return value / 3.3306953618655629312;
		}
		static toUSFluidOunces(value: number): number {
			return value / 0.026021057514574708736;
		}
		static toUSCups(value: number): number {
			return value / 0.20816846011659767808;
		}
		static toCubicMetres(value: number): number {
			return value / 879.877;
		}
		static toCubicFeet(value: number): number {
			return value / 24.9153;
		}
		static toCubicInches(value: number): number {
			return value * 69.3549;
		}
		static toOilBarrels(value: number): number {
			return value / 139.889;
		}
	}

	export class Tablespoons {
		static toMillilitres(value: number): number {
			return value * 17.758171402343747584;
		}
		static toLitres(value: number): number {
			return value * 0.017758171402343747584;
		}
		static toKilolitres(value: number): number {
			return value * 0.000017758171402343747;
		}
		static toTeaspoons(value: number): number {
			return value * 3.0;
		}
		static toQuarts(value: number): number {
			return value / 64.0;
		}
		static toPints(value: number): number {
			return value / 32.0;
		}
		static toGallons(value: number): number {
			return value / 256.0;
		}
		static toFluidOunces(value: number): number {
			return value / 1.6;
		}
		static toUSTeaspoons(value: number): number {
			return value / 0.27755794682213023744;
		}
		static toUSTablespoons(value: number): number {
			return value / 0.83267384046639071232;
		}
		static toUSQuarts(value: number): number {
			return value / 53.291125789849001984;
		}
		static toUSPints(value: number): number {
			return value / 26.645562894924500992;
		}
		static toUSGallons(value: number): number {
			return value / 213.16450315939602432;
		}
		static toUSFluidOunces(value: number): number {
			return value / 1.6653476809327814656;
		}
		static toUSCups(value: number): number {
			return value / 13.322781447462250496;
		}
		static toCubicMetres(value: number): number {
			return value / 56312.1;
		}
		static toCubicFeet(value: number): number {
			return value / 1594.58;
		}
		static toCubicInches(value: number): number {
			return value * 1.08367;
		}
		static toOilBarrels(value: number): number {
			return value / 8952.91;
		}
	}

	export class Teaspoons {
		static toMillilitres(value: number): number {
			return value * 5.9193904674479161344;
		}
		static toLitres(value: number): number {
			return value * 0.005919390467447916134;
		}
		static toKilolitres(value: number): number {
			return value * 0.000005919390467447916;
		}
		static toTablespoons(value: number): number {
			return value / 3.0;
		}
		static toQuarts(value: number): number {
			return value / 192.0;
		}
		static toPints(value: number): number {
			return value / 96.0;
		}
		static toGallons(value: number): number {
			return value / 768.0;
		}
		static toFluidOunces(value: number): number {
			return value / 4.8;
		}
		static toUSTeaspoons(value: number): number {
			return value / 0.83267384046639071232;
		}
		static toUSTablespoons(value: number): number {
			return value / 2.4980215213991718912;
		}
		static toUSQuarts(value: number): number {
			return value / 159.87337736954701824;
		}
		static toUSPints(value: number): number {
			return value / 79.936688684773507072;
		}
		static toUSGallons(value: number): number {
			return value / 639.49350947818807296;
		}
		static toUSFluidOunces(value: number): number {
			return value / 4.9960430427983437824;
		}
		static toUSCups(value: number): number {
			return value / 39.968344342386753536;
		}
		static toCubicMetres(value: number): number {
			return value / 168936.0;
		}
		static toCubicFeet(value: number): number {
			return value / 4783.74;
		}
		static toCubicInches(value: number): number {
			return value / 2.76837;
		}
		static toOilBarrels(value: number): number {
			return value / 26858.7;
		}
	}

	export class USCups {
		static toMillilitres(value: number): number {
			return value * 236.58823649999998976;
		}
		static toLitres(value: number): number {
			return value * 0.23658823649999998976;
		}
		static toKilolitres(value: number): number {
			return value * 0.000236588236499999989;
		}
		static toTeaspoons(value: number): number {
			return value * 39.968344342386753536;
		}
		static toTablespoons(value: number): number {
			return value * 13.322781447462250496;
		}
		static toQuarts(value: number): number {
			return value * 0.20816846011659767808;
		}
		static toPints(value: number): number {
			return value * 0.41633692023319535616;
		}
		static toGallons(value: number): number {
			return value * 0.052042115029149417472;
		}
		static toFluidOunces(value: number): number {
			return value * 8.3267384046639071232;
		}
		static toUSTeaspoons(value: number): number {
			return value * 48.0;
		}
		static toUSTablespoons(value: number): number {
			return value * 16.0;
		}
		static toUSQuarts(value: number): number {
			return value / 4.0;
		}
		static toUSPints(value: number): number {
			return value / 2.0;
		}
		static toUSGallons(value: number): number {
			return value / 16.0;
		}
		static toUSFluidOunces(value: number): number {
			return value * 8.0;
		}
		static toCubicMetres(value: number): number {
			return value / 4166.67;
		}
		static toCubicFeet(value: number): number {
			return value / 117.987;
		}
		static toCubicInches(value: number): number {
			return value * 14.6457;
		}
		static toOilBarrels(value: number): number {
			return value / 662.447;
		}
	}

	export class USFluidOunces {
		static toMillilitres(value: number): number {
			return value * 29.573529562499997696;
		}
		static toLitres(value: number): number {
			return value * 0.029573529562499997696;
		}
		static toKilolitres(value: number): number {
			return value * 0.0000295735296;
		}
		static toTeaspoons(value: number): number {
			return value * 4.9960430427983437824;
		}
		static toTablespoons(value: number): number {
			return value * 1.6653476809327814656;
		}
		static toQuarts(value: number): number {
			return value * 0.026021057514574708736;
		}
		static toPints(value: number): number {
			return value * 0.052042115029149417472;
		}
		static toGallons(value: number): number {
			return value * 0.006505264378643677184;
		}
		static toFluidOunces(value: number): number {
			return value * 1.0408423005829883904;
		}
		static toUSTeaspoons(value: number): number {
			return value * 6.0;
		}
		static toUSTablespoons(value: number): number {
			return value * 2.0;
		}
		static toUSQuarts(value: number): number {
			return value / 32.0;
		}
		static toUSPints(value: number): number {
			return value / 16.0;
		}
		static toUSGallons(value: number): number {
			return value / 128.0;
		}
		static toUSCups(value: number): number {
			return value / 8.0;
		}
		static toCubicMetres(value: number): number {
			return value / 33814.0;
		}
		static toCubicFeet(value: number): number {
			return value / 957.506;
		}
		static toCubicInches(value: number): number {
			return value * 1.80469;
		}
		static toOilBarrels(value: number): number {
			return value / 5376.0;
		}
	}

	export class USGallons {
		static toMillilitres(value: number): number {
			return value * 3785.411784;
		}
		static toLitres(value: number): number {
			return value * 3.785411784;
		}
		static toKilolitres(value: number): number {
			return value * 0.003785411784;
		}
		static toTeaspoons(value: number): number {
			return value * 639.49350947818807296;
		}
		static toTablespoons(value: number): number {
			return value * 213.16450315939602432;
		}
		static toQuarts(value: number): number {
			return value * 3.3306953618655629312;
		}
		static toPints(value: number): number {
			return value * 6.6613907237311258624;
		}
		static toGallons(value: number): number {
			return value * 0.83267384046639071232;
		}
		static toFluidOunces(value: number): number {
			return value * 133.22781447462252544;
		}
		static toUSTeaspoons(value: number): number {
			return value * 768.0;
		}
		static toUSTablespoons(value: number): number {
			return value * 256.0;
		}
		static toUSQuarts(value: number): number {
			return value * 4.0;
		}
		static toUSPints(value: number): number {
			return value * 8.0;
		}
		static toUSFluidOunces(value: number): number {
			return value * 128.0;
		}
		static toUSCups(value: number): number {
			return value * 16.0;
		}
		static toCubicMetres(value: number): number {
			return value / 264.172;
		}
		static toCubicFeet(value: number): number {
			return value / 7.48052;
		}
		static toCubicInches(value: number): number {
			return value * 231.0;
		}
		static toOilBarrels(value: number): number {
			return value / 42.0;
		}
	}

	export class USPints {
		static toMillilitres(value: number): number {
			return value * 473.17647299999997952;
		}
		static toLitres(value: number): number {
			return value * 0.47317647299999997952;
		}
		static toKilolitres(value: number): number {
			return value * 0.000473176472999999979;
		}
		static toTeaspoons(value: number): number {
			return value * 79.936688684773507072;
		}
		static toTablespoons(value: number): number {
			return value * 26.645562894924500992;
		}
		static toQuarts(value: number): number {
			return value * 0.41633692023319535616;
		}
		static toPints(value: number): number {
			return value * 0.83267384046639071232;
		}
		static toGallons(value: number): number {
			return value * 0.10408423005829883904;
		}
		static toFluidOunces(value: number): number {
			return value * 16.653476809327814656;
		}
		static toUSTeaspoons(value: number): number {
			return value * 96.0;
		}
		static toUSTablespoons(value: number): number {
			return value * 32.0;
		}
		static toUSQuarts(value: number): number {
			return value / 2.0;
		}
		static toUSGallons(value: number): number {
			return value / 8.0;
		}
		static toUSFluidOunces(value: number): number {
			return value * 16.0;
		}
		static toUSCups(value: number): number {
			return value * 2.0;
		}
		static toCubicMetres(value: number): number {
			return value / 2113.38;
		}
		static toCubicFeet(value: number): number {
			return value / 59.8442;
		}
		static toCubicInches(value: number): number {
			return value * 28.875;
		}
		static toOilBarrels(value: number): number {
			return value / 336.0;
		}
	}

	export class USQuarts {
		static toMillilitres(value: number): number {
			return value * 946.35294599999995904;
		}
		static toLitres(value: number): number {
			return value * 0.94635294599999995904;
		}
		static toKilolitres(value: number): number {
			return value * 0.000946352945999999959;
		}
		static toTeaspoons(value: number): number {
			return value * 159.87337736954701824;
		}
		static toTablespoons(value: number): number {
			return value * 53.291125789849001984;
		}
		static toQuarts(value: number): number {
			return value * 0.83267384046639071232;
		}
		static toPints(value: number): number {
			return value * 1.6653476809327814656;
		}
		static toGallons(value: number): number {
			return value * 0.20816846011659767808;
		}
		static toFluidOunces(value: number): number {
			return value * 33.306953618655629312;
		}
		static toUSTeaspoons(value: number): number {
			return value * 192.0;
		}
		static toUSTablespoons(value: number): number {
			return value * 64.0;
		}
		static toUSPints(value: number): number {
			return value * 2.0;
		}
		static toUSGallons(value: number): number {
			return value / 4.0;
		}
		static toUSFluidOunces(value: number): number {
			return value * 32.0;
		}
		static toUSCups(value: number): number {
			return value * 4.0;
		}
		static toCubicMetres(value: number): number {
			return value / 1056.69;
		}
		static toCubicFeet(value: number): number {
			return value / 29.9221;
		}
		static toCubicInches(value: number): number {
			return value * 57.75;
		}
		static toOilBarrels(value: number): number {
			return value / 168.0;
		}
	}

	export class USTablespoons {
		static toMillilitres(value: number): number {
			return value * 14.786764781249998848;
		}
		static toLitres(value: number): number {
			return value * 0.014786764781249998848;
		}
		static toKilolitres(value: number): number {
			return value * 0.000014786764781249998;
		}
		static toTeaspoons(value: number): number {
			return value * 2.4980215213991718912;
		}
		static toTablespoons(value: number): number {
			return value * 0.83267384046639071232;
		}
		static toQuarts(value: number): number {
			return value * 0.013010528757287354368;
		}
		static toPints(value: number): number {
			return value * 0.026021057514574708736;
		}
		static toGallons(value: number): number {
			return value * 0.003252632189321838592;
		}
		static toFluidOunces(value: number): number {
			return value * 0.52042115029149417472;
		}
		static toUSTeaspoons(value: number): number {
			return value * 3.0;
		}
		static toUSQuarts(value: number): number {
			return value / 64.0;
		}
		static toUSPints(value: number): number {
			return value / 32.0;
		}
		static toUSGallons(value: number): number {
			return value / 256.0;
		}
		static toUSFluidOunces(value: number): number {
			return value / 2.0;
		}
		static toUSCups(value: number): number {
			return value / 16.0;
		}
		static toCubicMetres(value: number): number {
			return value / 67628.0;
		}
		static toCubicFeet(value: number): number {
			return value / 1915.01;
		}
		static toCubicInches(value: number): number {
			return value / 1.10823;
		}
		static toOilBarrels(value: number): number {
			return value / 10752.0;
		}
	}

	export class USTeaspoons {
		static toMillilitres(value: number): number {
			return value * 4.928921593749999616;
		}
		static toLitres(value: number): number {
			return value * 0.004928921593749999616;
		}
		static toKilolitres(value: number): number {
			return value * 0.000004928921593749999;
		}
		static toTeaspoons(value: number): number {
			return value * 0.83267384046639071232;
		}
		static toTablespoons(value: number): number {
			return value * 0.27755794682213023744;
		}
		static toQuarts(value: number): number {
			return value * 0.004336842919095784243;
		}
		static toPints(value: number): number {
			return value * 0.008673685838191568486;
		}
		static toGallons(value: number): number {
			return value * 0.00108421072977394606;
		}
		static toFluidOunces(value: number): number {
			return value * 0.1734737167638313984;
		}
		static toUSTablespoons(value: number): number {
			return value / 3.0;
		}
		static toUSQuarts(value: number): number {
			return value / 192.0;
		}
		static toUSPints(value: number): number {
			return value / 96.0;
		}
		static toUSGallons(value: number): number {
			return value / 768.0;
		}
		static toUSFluidOunces(value: number): number {
			return value / 6.0;
		}
		static toUSCups(value: number): number {
			return value / 48.0;
		}
		static toCubicMetres(value: number): number {
			return value / 202884.0;
		}
		static toCubicFeet(value: number): number {
			return value / 5745.04;
		}
		static toCubicInches(value: number): number {
			return value / 3.32468;
		}
		static toOilBarrels(value: number): number {
			return value / 32256.0;
		}
	}
}
